### ISSUE TITLE
How to set font `Microsoft YaHei`

### ISSUE THREAD

**Issue by gclsoft** [tnfe/FFCreator#10]
const ftext = new FFText({text, x: width / 2, y: height - 50, fontSize: 25});
  ftext.setColor('#fff');
  ftext.setFont("微软雅黑")
 // ftext.setFont("Microsoft YaHei")
OR:
var pathNameFont = "./assets/fonts/msyh.ttf";
const FONT_PATH = path.join(__dirname, pathNameFont);
  ftext.setFont(FONT_PATH)

Doesn't work.
```

(process:12272): Pango-WARNING **: 00:40:24.754: couldn't load font " Not-Rotated 25px", falling back to "Sans Not-Rotated 25px", expect ugly output.

(process:12272): Pango-WARNING **: 00:40:24.815: couldn't load font "  25px", falling back to "Sans 25px", expect ugly output.
```

**Comment by drawcall** [comment]
Oh, if you want to use a font in FFCreator, you must install the font on your running machine. If you want to use a font in FFCreatorLite, you can directly pass in the font file path through setFont.

**Comment by drawcall** [comment]
In fact, I prefer FFCreatorLite, it’s faster and has many unique features

**Comment by gclsoft** [comment]
![image](https://user-images.githubusercontent.com/1269898/99813135-45b27c00-2b82-11eb-83c2-ef66afca8e5d.png)
I had installed on my machine, but not work
```
ftext.setFont("微软雅黑")
// ftext.setFont("Microsoft YaHei")
```
I can't use FFCreatorLite, because it doesn't support `FFSubtitle`

**Comment by drawcall** [comment]
Oh, thank you for your careful testing work.

Please upgrade to v1.3.5, Use as follows

```
const font = path.join(__dirname, './assets/font/yahei.ttf');
text.setFont(font);
```

**Comment by wwqking** [comment]
请问是哪个依赖升级到v1.3.5

**Comment by 868618** [comment]
同问

(process:5916): Pango-WARNING **: 09:07:10.871: couldn't load font "LiXuKe Not-Rotated 217px", falling back to "Sans Not-Rotated 217px", expect ugly output.

(process:5916): Pango-WARNING **: 09:07:10.893: couldn't load font "LiXuKe 217px", falling back to "Sans 217px", expect ugly output.

请问是哪个依赖升级到v1.3.5
