### ISSUE TITLE
关于同时设置音乐的start以及fadeIn所出现的问题

### ISSUE THREAD

**Issue by zhuzengguan** [tnfe/FFCreator#106]
当同时设置了音乐的开始时间以及淡入效果的时候，音乐播放会出现异常

打开ffmpeg合成日志发现[1]adelay=2000|2000,volume=0.8,**afade=t=in:st=2000:d=3**,afade=t=out:st=13:d=3[audio0]
指出其中 关于音乐淡入的ffmpeg 命令 **st**之后的单位应该为秒

个人简单的解决方法：将audio目录下的audio.js文件中的
 toFadeInFilter() {
    const { fadeIn = -1, delay } = this;
    if (fadeIn === -1) return '';
    return `,afade=t=in:st=${delay}:d=${fadeIn}`;
  }
修改为
 toFadeInFilter() {
    const { fadeIn = -1, delay } = this;
    if (fadeIn === -1) return '';
    return `,afade=t=in:st=${delay/1000}:d=${fadeIn}`;
  }

**Comment by drawcall** [comment]
Oh, please download the latest version.

**Comment by drawcall** [comment]
Are you interested in creating a video site based on FFCreator+LowCode.

**Comment by zhuzengguan** [comment]
> Are you interested in creating a video site based on FFCreator+LowCode.
I think your idea is very feasible, but I don't know much about LowCode.
