### ISSUE TITLE
How to set text's delay time?

### ISSUE THREAD

**Issue by gclsoft** [tnfe/FFCreator#11]
If the text is too long, I want to display first one text in 2 seconds then the second text in 2 seconds later, they both display in one scene. How to make it ?
```
const creatText=(text,duration)=>{
  const ftext = new FFText({text, x: width / 2, y: height - 50, fontSize: 25});
  ftext.setColor('#fff');
  ftext.setFont(FONT_PATH)
  // ftext.setFont("Microsoft YaHei")
  // ftext.alignCenter();
  ftext.setAnchor(0.5);
  ftext.setStyle({textAlign: 'bottom'});
  //ftext.setBackgroundColor('#ffffff');
//  ftext.addEffect('fadeInRight', 1, 1.3);
  ftext.setStyle({padding: [4, 12, 6, 12]});
  ftext.setDuration(duration);//ANIMATE_TIME/2);
  //ftext.addEffect()
  return ftext;
}

  // title text
  if ((text.length)>9){
    let texts=text.split("。")
    let size=(texts).length
    for (let t in texts){
      let ftext=creatText(t,ANIMATE_TIME/size)
      scene.addChild(ftext);
    }
  }else{
    let ftext=creatText(text,ANIMATE_TIME)
    scene.addChild(ftext);
  }
```

**Comment by drawcall** [comment]
Oh, there are two solutions to your problem.
1. Use addEffect to set the delay parameter [https://tnfe.github.io/FFCreator/#/guide/animate](https://tnfe.github.io/FFCreator/#/guide/animate)

```
text1.addEffect('fadeIn', .7, 0.1);
text1.addEffect('fadeOut', .5, 2);
text2.addEffect('fadeIn', .7, 2);
```

2. Use subtitle components to achieve your goals

**Comment by gclsoft** [comment]
Thanks very much @drawcall !
But opacity doesn't support `FFSubtitle`, how to make `FFSubtitle` transparency?
```
  const subtitle = new FFSubtitle({
    comma: false, // 是否逗号分割
    backgroundColor: '#444359',
    color: '#fff',
    fontSize: 18,
    x: width / 2,
    y: height - 50
  });
  subtitle.setFont("微软雅黑")//FONT_PATH")

  subtitle.setText(text);
  const tts = path.join(__dirname, './assets/audio/tts.wav');
  subtitle.setSpeech(""); // 语音配音-tts
  subtitle.frameBuffer = 24;
  subtitle.setDuration(SCENE_DURATION)
  subtitle.setOpacity(0)
  scene.addChild(subtitle);
```

**Comment by drawcall** [comment]
Oh, why do you set ffsubtitle to opacity 0? If you want to make animation, you can use addeffect

**Comment by gclsoft** [comment]
> Oh, why do you set ffsubtitle to opacity 0? If you want to make animation, you can use addeffect

Because I don't need the background color of the  FFSubtitle. I don't need the effect either

**Comment by drawcall** [comment]
``` 
const subtitle = new FFSubtitle({
    comma: false, // 是否逗号分割
    // backgroundColor: '#444359',
    color: '#fff',
    fontSize: 18,
    x: width / 2,
    y: height - 50
  });
```

You don't need to set the backgroundColor parameter

**Comment by gclsoft** [comment]
> backgroundColor

![image](https://user-images.githubusercontent.com/1269898/99865679-67dde580-2be6-11eb-89d9-6b670c658daf.png)
Not work. It will auto set to this color.

**Comment by gclsoft** [comment]
![image](https://user-images.githubusercontent.com/1269898/99865738-dfac1000-2be6-11eb-802d-c662b56812cd.png)

**Comment by drawcall** [comment]
Oh yes, I set the default value here. You need to set the backgroundColor to `undefined`. I want to think about how to provide a more friendly API

**Comment by gclsoft** [comment]
Thanks! 
 setDefaultStyle() {
   const padding = [4, 12, 6, 12];
   const {color = '#ffffff'} = this.conf;
   this.setStyle({color, padding, opacity: 0});
  }
