### ISSUE TITLE
animate延时超过100秒就会立马执行导致出问题，原因出自下图代码出，不知用意是什么

### ISSUE THREAD

**Issue by superzay** [tnfe/FFCreator#110]
![image](https://user-images.githubusercontent.com/28672461/133637042-10003e00-80f6-4f37-8e00-20b13ac226a8.png)

**Comment by drawcall** [comment]
Oh that was a fault-tolerant solution, OK now I give up.

**Comment by whl88** [comment]
上图中的 toSeconds(time) 可能也需要小改一下。^_^

**Comment by drawcall** [comment]
View latest version
