### ISSUE TITLE
InkPaint 的 BlurFilter() 在 FFCreator 不可用

### ISSUE THREAD

**Issue by jianshuo** [tnfe/FFCreator#113]
按照InkPaint的文档，应该可以设置filter。

在FFCreator里面，

```
const video = new FFCreator()
video.path = '....'
video.display.blur = 20
```

如上代码不work。

或者用其他的方式，
```
.......
video.display.filters = [new BlurFilter()]
```

也没有blur效果。

不知道有可否分享在FFCreator里面使用到InkPaint的各种强大的功能的方法？多谢！

**Comment by drawcall** [comment]
Oh, I didn’t add this filter, maybe I will add it later.

**Comment by drawcall** [comment]
Configuration settings:
render: "gl"

Use setBulr to set the blur filter, currently only supports blur
