### ISSUE TITLE
在两个 FFScene 之间不设置 transition 会导致 FFScene 与 FFScene 之间有黑帧

### ISSUE THREAD

**Issue by whl88** [tnfe/FFCreator#116]
大神你好，在两个 FFScene 之间不设置 transition 会导致 FFScene 与 FFScene 之间有黑帧，在浅色视频中会闪一下，感官很明显。

## 复现方法：

1. ### 修改官方示例代码 examples/transition.js，注释掉下图中的第68行。

![image-20210922161933542](https://user-images.githubusercontent.com/28629101/134309457-92d61bc1-064b-4bf7-afaa-79bd99ca73f3.png)

2. ### ffmpeg 提取帧。

```shell
ffmpeg.exe -i xiltirdf5n1obc9e.mp4 ./img/%d.png
```
![image](https://user-images.githubusercontent.com/28629101/134309903-04ae3754-47cd-41a7-817a-0b67eea74b8d.png)

**Comment by drawcall** [comment]
Has been fixed, please help test

**Comment by whl88** [comment]
Great, the test passed. Thank you
