### ISSUE TITLE
可否保留序列帧方式创建 FFVtuber ，setCutoutColor 方式扣绿幕效果不太好，有毛边

### ISSUE THREAD

**Issue by whl88** [tnfe/FFCreator#117]
你好，通过绿幕视频 + setCutoutColor 的方式创建 FFVtuber 很难避免扣绿幕的误差。可否将这一部分开放出来，让使用者有机会通过预处理的方式来做，之前我们是通过机器学习将序列帧处理到几近完美，然后用序列帧创建 FFVtuber的。

> Tip: 对于扣人形图，`tensorflow`的 [body-pix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix)可以发挥作用，但也只限人形图。

![image-20210922200806827](https://user-images.githubusercontent.com/28629101/134343584-bb2b089e-6d1f-4dcb-9cb2-74433db6bd63.png)

**Comment by drawcall** [comment]
OK mark了, 精力有限 暂时没法很快迭代

**Comment by whl88** [comment]
great !! thank you !! @drawcall
