### ISSUE TITLE
Include a waveform in the video

### ISSUE THREAD

**Issue by armandoarmando** [tnfe/FFCreator#121]
Hello everybody, I'm using the library and works great, but now my client wants to show the audio waveform in the video. Is it possible with FFCreator? 

Thanks!
Armando

**Comment by drawcall** [comment]
Oh, very good idea: But the waveform is a customized element, not suitable as a component. 
You can use FFExtras to write.

**Comment by armandoarmando** [comment]
how can I use FFExtras? I can't find it in the docs. Thanks

**Comment by drawcall** [comment]
This is a hidden api, you can view the source code.
