### ISSUE TITLE
关于渲染时的异步/同步问题

### ISSUE THREAD

**Issue by windschaser** [tnfe/FFCreator#127]
一个task开始后，整个阶段都是异步的吗？这里说的异步是渲染任务在另一个进程上执行，不占用当前进程，从而可以继续处理请求。

从测试来看，Windows平台上是ok的，任意多个请求都会正常入队并等待调度；在Centos上，会出现疑似阻塞现象，一个任务开始后，这个进程就无法再接受新的请求了，直到任务渲染完成。部分情况下可以接受请求，但是业务代码的执行会受到影响，出现较长的延迟执行情况。

作为对比，直接使用fluent-ffmpeg渲染的任务不受影响，在Windows/Centos上都可以正常入队（自行实现了ffmpeg和FFC
reatorCenter的桥接）。

可能的猜测：gl或者其他依赖在不同平台上的表现不一致，或者，emmm

期待解答或者任何思路。

**Comment by drawcall** [comment]
What is the cpu and memory configuration of your Linux machine, it may be that the cpu calculation is blocking the event loop. Of course, there are many optimization methods here, if I have time.

**Comment by drawcall** [comment]
https://github.com/tnfe/FFCreator/issues/149

**Comment by xeoshow** [comment]
highWaterMark 的经验值在多少范围比较合适呢？是否机器配置高，值就可以相对设置大一些？谢谢
