### ISSUE TITLE
Remove border from video

### ISSUE THREAD

**Issue by armandolio** [tnfe/FFCreator#129]
Hello guys! when I create a video, it's creating well but its adding an extra border (I did not add it)
How can I remove it?

Thanks

![image](https://user-images.githubusercontent.com/46790753/137271669-7901cb25-af36-4331-8c3f-1646b65a43ed.png)

**Comment by drawcall** [comment]
Please upload the project or submit the code

**Comment by armandoarmando** [comment]
thank you very much!!
