### ISSUE TITLE
the 11th and 12th tts wav, are combined to the 1st scene's tts. I guess the 13th tts is also combined to the 1st scene tts too.

### ISSUE THREAD

**Issue by gclsoft** [tnfe/FFCreator#13]
```
const transitionDemoTask = async () => {

}
{
  const subtitle = new FFSubtitle({
    comma: false, // 是否逗号分割
    backgroundColor: '#444359',
    color: '#fff',
    fontSize: 24,
    x: width / 2,
    y: height - 50
  });
  subtitle.setFont("Simsun")//FONT_PATH")
  subtitle.setText(text);
  subtitle.setSpeech(ttsFile); // 语音配音-tts
  subtitle.frameBuffer = 24;
  subtitle.setDuration(SCENE_DURATION)
  scene.addAudio(ttsFile)
  scene.addChild(subtitle);
  return scene;
};
FFCreatorCenter.addTask(transitionDemoTask)

```
the 11th and 12th tts wav, are combined to the 1st scene's tts. I guess the 13th tts is also combined to the 1st scene tts too.
 I don't know why. I checked my code, no problems found.
Is it a bug in FFCreator?
![image](https://user-images.githubusercontent.com/1269898/99910055-f22d6300-2d26-11eb-8c60-b4f7e00652ef.png)

**Comment by gclsoft** [comment]
It can't add more than 11 wav files to 11 scenes, when the 12th scene's addAudio is set, it will be added to the 1st scene.

**Comment by gclsoft** [comment]
I found another problem, the wave sound volume is not the same as the wave origin, the last waves have a lot higher volume than the first ones, while in the origin waves, the volums are the same .

**Comment by gclsoft** [comment]
```
ffmpeg -framerate 60 -vcodec rawvideo -pixel_format bgra -video_size 600x400 -i C:\work\newml\ffcreator\examples\cache\afjomdcnh78snf3d\%012d.raw -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\0.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\1.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\2.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\3.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\4.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\5.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\6.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\7.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\8.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\9.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\10.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\11.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\12.wav -y -filter_complex [1]adelay=0|0[audio0];[2]adelay=5312.75|5312.75[audio1];[3]adelay=17706.375|17706.375[audio2];[4]adelay=28624.6875|28624.6875[audio3];[5]adelay=35950.625|35950.625[audio4];[6]adelay=50769.875|50769.875[audio5];[7]adelay=64506.31249999999|64506.31249999999[audio6];[8]adelay=80.43324999999999|80.43324999999999[audio7];[9]adelay=94.82193749999999|94.82193749999999[audio8];[10]adelay=109.8145625|109.8145625[audio9];[11]adelay=120.89462499999999|120.89462499999999[audio10];[12]adelay=136.6285625|136.6285625[audio11];[13]adelay=144.2374375|144.2374375[audio12];[audio0][audio1][audio2][audio3][audio4][audio5][audio6][audio7][audio8][audio9][audio10][audio11][audio12]amix=13 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 24 -c:a aac -shortest C:\work\newml\ffcreator\examples\output\藏.mp4
```
This is what I print from the ffmpeg, how ever It can't process from the command line. How to fix the problem?

**Comment by drawcall** [comment]
> ```
> ffmpeg -framerate 60 -vcodec rawvideo -pixel_format bgra -video_size 600x400 -i C:\work\newml\ffcreator\examples\cache\afjomdcnh78snf3d\%012d.raw -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\0.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\1.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\2.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\3.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\4.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\5.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\6.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\7.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\8.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\9.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\10.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\11.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\12.wav -y -filter_complex [1]adelay=0|0[audio0];[2]adelay=5312.75|5312.75[audio1];[3]adelay=17706.375|17706.375[audio2];[4]adelay=28624.6875|28624.6875[audio3];[5]adelay=35950.625|35950.625[audio4];[6]adelay=50769.875|50769.875[audio5];[7]adelay=64506.31249999999|64506.31249999999[audio6];[8]adelay=80.43324999999999|80.43324999999999[audio7];[9]adelay=94.82193749999999|94.82193749999999[audio8];[10]adelay=109.8145625|109.8145625[audio9];[11]adelay=120.89462499999999|120.89462499999999[audio10];[12]adelay=136.6285625|136.6285625[audio11];[13]adelay=144.2374375|144.2374375[audio12];[audio0][audio1][audio2][audio3][audio4][audio5][audio6][audio7][audio8][audio9][audio10][audio11][audio12]amix=13 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 24 -c:a aac -shortest C:\work\newml\ffcreator\examples\output\藏.mp4
> ```
> 
> This is what I print from the ffmpeg, how ever It can't process from the command line. How to fix the problem?

The log information is only used to assist in troubleshooting, and cannot be executed directly. You can learn the usage of ffmpeg before asking questions.

**Comment by gclsoft** [comment]
```
fileNameFull=assets\res\xizang\100000016.jpg
ttsFile=C:\work\newml\ffcreator\examples\assets\res\xizang\wav\12.wav
SCENE_DURATION=9
ANIMATE_TIME=9
FFCreator start
FFCreator progress: render-frame 0%
FFCreator progress: render-frame 10%
FFCreator progress: render-frame 20%
FFCreator progress: render-frame 30%
FFCreator progress: render-frame 40%
FFCreator progress: render-frame 50%
FFCreator progress: render-frame 60%
FFCreator progress: save-frame 70%
FFCreator progress: save-frame 80%
ffmpeg -framerate 60 -vcodec rawvideo -pixel_format bgra -video_size 600x400 -i C:\work\newml\ffcreator\examples\cache\eur804v8ky5ohlbc\%012d.raw -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\0.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\1.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\2.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\3.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\4.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\5.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\6.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\7.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\8.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\9.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\10.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\11.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\12.wav -y -filter_complex [1]adelay=0|0[audio0];[2]adelay=6000|6000[audio1];[3]adelay=19000|19000[audio2];[4]adelay=30000|30000[audio3];[5]adelay=38000|38000[audio4];[6]adelay=53000|53000[audio5];[7]adelay=67000|67000[audio6];[8]adelay=83|83[audio7];[9]adelay=98|98[audio8];[10]adelay=113|113[audio9];[11]adelay=125|125[audio10];[12]adelay=141|141[audio11];[13]adelay=149|149[audio12];[audio0][audio1][audio2][audio3][audio4][audio5][audio6][audio7][audio8][audio9][audio10][audio11][audio12]amix=13 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 24 -c:a aac -shortest C:\work\newml\ffcreator\examples\output\藏.mp4
FFCreator progress: synthesis-video 100%
FFCreator completed: 
 USEAGE: time 250927 memory 28609936 34545664 82.8% 271990784 cpu 48.6% 
 --- OK! --- 
```
After set scene and subtitle time to number, the same, 3 tts wavs in the first scene. The last scene's image is missing.

**Comment by drawcall** [comment]
> After set scene and subtitle time to number, the same, 3 tts wavs in the first scene. The last scene's image is missing.
> 
> Please check your code carefully before submitting an issue. only one tts file can be added to a scene, please do not use extreme cases to test. I hope you submit some PRs, I am a little busy recently

After set scene and subtitle time to number, the same, 3 tts wavs in the first scene. The last scene's image is missing.

Please check your code carefully before submitting an issue. only one tts file can be added to a scene, please do not use extreme cases to test. I hope you submit some PRs, I am a little busy recently

**Comment by drawcall** [comment]
> ```
> fileNameFull=assets\res\xizang\100000016.jpg
> ttsFile=C:\work\newml\ffcreator\examples\assets\res\xizang\wav\12.wav
> SCENE_DURATION=9
> ANIMATE_TIME=9
> FFCreator start
> FFCreator progress: render-frame 0%
> FFCreator progress: render-frame 10%
> FFCreator progress: render-frame 20%
> FFCreator progress: render-frame 30%
> FFCreator progress: render-frame 40%
> FFCreator progress: render-frame 50%
> FFCreator progress: render-frame 60%
> FFCreator progress: save-frame 70%
> FFCreator progress: save-frame 80%
> ffmpeg -framerate 60 -vcodec rawvideo -pixel_format bgra -video_size 600x400 -i C:\work\newml\ffcreator\examples\cache\eur804v8ky5ohlbc\%012d.raw -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\0.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\1.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\2.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\3.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\4.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\5.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\6.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\7.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\8.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\9.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\10.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\11.wav -i C:\work\newml\ffcreator\examples\assets\res\xizang\wav\12.wav -y -filter_complex [1]adelay=0|0[audio0];[2]adelay=6000|6000[audio1];[3]adelay=19000|19000[audio2];[4]adelay=30000|30000[audio3];[5]adelay=38000|38000[audio4];[6]adelay=53000|53000[audio5];[7]adelay=67000|67000[audio6];[8]adelay=83|83[audio7];[9]adelay=98|98[audio8];[10]adelay=113|113[audio9];[11]adelay=125|125[audio10];[12]adelay=141|141[audio11];[13]adelay=149|149[audio12];[audio0][audio1][audio2][audio3][audio4][audio5][audio6][audio7][audio8][audio9][audio10][audio11][audio12]amix=13 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 24 -c:a aac -shortest C:\work\newml\ffcreator\examples\output\藏.mp4
> FFCreator progress: synthesis-video 100%
> FFCreator completed: 
>  USEAGE: time 250927 memory 28609936 34545664 82.8% 271990784 cpu 48.6% 
>  --- OK! --- 
> ```
> 
> After set scene and subtitle time to number, the same, 3 tts wavs in the first scene. The last scene's image is missing.

Please check your code carefully before submitting an issue. only one tts file can be added to a scene, please do not use extreme cases to test. I hope you submit some PRs, I am a little busy recently

**Comment by gclsoft** [comment]
Sorry to use your time. I mean I set the one tts to only one scene, but the result is not good, it makes the last 3 waves to the first scene.
Thanks very much.&nbsp;I learn to&nbsp;submit&nbsp;PRs.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "anonymous namespace"<notifications@github.com&gt;; 
发送时间: 2020年11月26日(星期四) 下午3:20
收件人: "tnfe/FFCreator"<FFCreator@noreply.github.com&gt;; 
抄送: "g"<gclsoft@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tnfe/FFCreator] the 11th and 12th tts wav, are combined to the 1st scene&#39;s tts. I guess the 13th tts is also combined to the 1st scene tts too. (#13)





  
After set scene and subtitle time to number, the same, 3 tts wavs in the first scene. The last scene's image is missing.
 
Please check your code carefully before submitting an issue. only one tts file can be added to a scene, please do not use extreme cases to test. I hope you submit some PRs, I am a little busy recently
  
After set scene and subtitle time to number, the same, 3 tts wavs in the first scene. The last scene's image is missing.
 
Please check your code carefully before submitting an issue. only one tts file can be added to a scene, please do not use extreme cases to test. I hope you submit some PRs, I am a little busy recently
 
&mdash;
