### ISSUE TITLE
插入的FFVideo超过1分40秒，视频画面定格在1分40秒

### ISSUE THREAD

**Issue by whl88** [tnfe/FFCreator#132]
### 修改官方demo `examples/video.js`
![image](https://user-images.githubusercontent.com/28629101/137429423-f3bc6b60-5046-4467-9960-c9c353fa7751.png)
![image](https://user-images.githubusercontent.com/28629101/137437994-f6c0e621-9f9f-4489-8986-f4ca5f2fe725.png)
![image](https://user-images.githubusercontent.com/28629101/137429519-884ccdc8-a4e5-4c33-bfd3-f7a3be704dea.png)

### 控制台信息
![image](https://user-images.githubusercontent.com/28629101/137438326-514b8214-33d9-41fc-95e6-ab79242ef00e.png)

**Comment by drawcall** [comment]
Please copy the complete code

**Comment by drawcall** [comment]
Oh, because your video is over, you can set the loop

**Comment by drawcall** [comment]
Oh it has been fixed thanks
