### ISSUE TITLE
FFCreatorCenter.getTaskState返回一直是waiting，FFCreatorCenter.getResultFile返回undefined

### ISSUE THREAD

**Issue by Slash214** [tnfe/FFCreator#135]
你好，在阅读了官方文档使用koa2框架去实现的过程碰到了一些问题，希望可以得到解决。在获取工程进度的路由我使用了正确的taskid获取到了正确的加工进度，但通过FFCreatorCenter.getTaskState去获取工程任务的状态时显示的还是为waiting，但是FFCreatorCenter.getProgress(taskid)返回的值为1，视频也成功导出在我的output导出目录，但是无法正确获取进度状态，同时使用FFCreatorCenter.getResultFile方法去查询文件，返回的为undefined！

![image](https://user-images.githubusercontent.com/46257794/138389065-a91d13f9-c3cd-4286-ad3c-1f2abd00166d.png)
![image](https://user-images.githubusercontent.com/46257794/138389182-7e56a21a-3533-4178-9ffe-87f85df3e4aa.png)

**Comment by Slash214** [comment]
> Oh, you need to judge state === "complete" instead of progress===1.
Yes, I know, but the state is always waiting, I don't understand why?, and the video has been successfully exported！
![image](https://user-images.githubusercontent.com/46257794/138392441-ef1a919d-8736-4e7f-a6d2-9acb1db017bb.png)
![image](https://user-images.githubusercontent.com/46257794/138392444-43e4203f-434e-4b15-bd9e-e493af55ed93.png)

**Comment by drawcall** [comment]
Oh download the latest version and open the log, or please upload your project.
