### ISSUE TITLE
Cannot read property 'ARRAY_BUFFER' of null

### ISSUE THREAD

**Issue by hengyin1** [tnfe/FFCreator#136]
centos8中报Cannot read property 'ARRAY_BUFFER' of null

具体报错日志：Cannot read property 'ARRAY_BUFFER' of null
10/24 13:25:33
video-creater-066
    at FFTransition.createBuffer (/usr/src/app/node_modules/ffcreator/lib/animate/transition.js:73:45)
10/24 13:25:33
video-creater-066
    at FFTransition.createTransition (/usr/src/app/node_modules/ffcreator/lib/animate/transition.js:61:10)
10/24 13:25:33
video-creater-066
    at FFTransition.bindGL (/usr/src/app/node_modules/ffcreator/lib/animate/transition.js:40:10)
10/24 13:25:33
video-creater-066
    at /usr/src/app/node_modules/ffcreator/lib/core/renderer.js:119:57

**Comment by hjane** [comment]
请问你解决问题了吗？能告诉我一下如何解决吗？

**Comment by superzay** [comment]
我也遇到了同样的问题，处理步骤：

先按照下面的说明安装
![image](https://user-images.githubusercontent.com/28672461/142995428-b3dae9fa-4344-4cd5-ae66-9b25cdad17fe.png)

在按照下面的说明启动，我是直接用一个test.js进行测试的，所以命令是：xvfb-run -s "-ac -screen 0 1280x1024x24" node test.js
![image](https://user-images.githubusercontent.com/28672461/142995952-19418bce-144d-45f2-a9ca-c45ddab23600.png)



> 请问你解决问题了吗？能告诉我一下如何解决吗？

**Comment by superzay** [comment]
@hjane @hengyin1 
我也遇到了同样的问题，处理步骤：

**先按照下面的说明安装**
![image](https://user-images.githubusercontent.com/28672461/142997032-069231bd-3a8f-4f61-aef2-0a4ac89428e2.png)

**在按照下面的说明启动，我是直接用一个test.js进行测试的，所以命令是：xvfb-run -s "-ac -screen 0 1280x1024x24" node test.js**
![image](https://user-images.githubusercontent.com/28672461/142997129-fd1d75e0-2ca6-4c2e-8c06-3036908895b0.png)

**Comment by ljinkai** [comment]
@hengyin1 我也是centos8 中报这个错，请问你的问题解决了吗？ 我按上面说的方式安装了Linux下的ffmpeg，还是报这个错。
