### ISSUE TITLE
向场景中添加多张图片，怎样让图片依次显示？

### ISSUE THREAD

**Issue by hjane** [tnfe/FFCreator#138]
向场景中添加图片。0秒显示图1，持续3秒，3秒显示图2，持续3秒……
如果让图片依次显示？

**Comment by drawcall** [comment]
https://github.com/tnfe/FFCreator/blob/master/examples/album.js

**Comment by hjane** [comment]
> https://github.com/tnfe/FFCreator/blob/master/examples/album.js

你的意思是把图片放进相册内吗？我想知道有没有一个设置可以控制元素从什么时间起在场景中存在。比如一张图片我想在第3秒的时候在场景中展示，展示时长3秒。我以为setOffset()可以控制，但是我设置后无效。

**Comment by drawcall** [comment]
Use addEffect

**Comment by hjane** [comment]
> Use addEffect
非常感谢，addEffect 满足了我的需求。

**Comment by hjane** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件已经收到，我会在一周内尽快给您回复！
