### ISSUE TITLE
createEffect 添加的自定义动画没有正常消失

### ISSUE THREAD

**Issue by hjane** [tnfe/FFCreator#142]
当我处理一个图片的进入进出动画时，我用fadeIn和fadeOut可以正常显示和隐藏。
image.addEffect('fadeIn', 1, offset);
image.addEffect('fadeOut', 1, offset + duration - 1);
我定义了一个自定义的动画
creator.createEffect('scaleOut', {
  from: { opacity: 1, scale: 1 },
  to: { opacity: 0, scale: 1.3 },
  ease: 'Linear.None',
});
然后把fadeOut改为scaleOut，我预计图片应该放大并透明度变为0，从视频中消失。但图片只是放大，并没有消失，一直停留在场景中。
image.addEffect('scaleOut', 1, offset + duration - 1);

**Comment by z411500976** [comment]
[https://github.com/tnfe/FFCreator/issues/90]  May be the reason

**Comment by drawcall** [comment]
opacity -> alpha
