### ISSUE TITLE
ffcreator 生成视频时阻塞进程

### ISSUE THREAD

**Issue by hengyin1** [tnfe/FFCreator#149]
在Centos上，会出现阻塞现象，一个任务开始后，这个进程就无法再接受新的请求了，直到任务渲染完成

**Comment by drawcall** [comment]
Oh, what is your machine configuration. Maybe cpu consumption is blocking the event loop.

There are 3 solutions
1. Improve the machine configuration
2. Build a cluster to handle requests independently
3. Set render to gl mode, which will reduce cpu consumption
