### ISSUE TITLE
text的lineHeight设置后，backgroundColor没有正常的渲染

### ISSUE THREAD

**Issue by rulaishenzhang** [tnfe/FFCreator#151]
如下图：
文本设置了lineHeight后，添加backgroundColor时，文字应该是上下居中才对的。
![WX20211119-154823](https://user-images.githubusercontent.com/6290595/142585244-1cc50316-a6a7-4f7e-bead-70c73616f6dc.png)

**Comment by drawcall** [comment]
set padding
