### ISSUE TITLE
不支持mov，webm背景透明的视频

### ISSUE THREAD

**Issue by changqing91** [tnfe/FFCreator#157]
https://github.com/tnfe/FFCreator/blob/0e5b2c4ecee0dd5aa5952e337ea52085d295b1bb/lib/node/video.js#L345

为什么要写死输出jpg，透明的视频不就会变不透明了吗？

**Comment by drawcall** [comment]
Oh you can submit a pr

**Comment by changqing91** [comment]
https://github.com/tnfe/FFCreator/pull/159
已提交
