### ISSUE TITLE
Error: Cannot find module '../utils/Utils'

### ISSUE THREAD

**Issue by Cattosm** [tnfe/FFCreator#16]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../utils/Utils'

已经npm install utils了，怎么会报错呢？？

**Comment by drawcall** [comment]
Oh, make sure you started the project on the node side, not the web side

**Comment by Cattosm** [comment]
Thank you for the answer， now i run "xvfb-run -s "-ac -screen 0 800x600x24" npm start". however nothing happened ,no process running , no port up, also no errors reported

**Comment by drawcall** [comment]
Oh, there is too little information. Can you describe in detail your installation machine and node environment, operation steps and error messages

**Comment by Cattosm** [comment]
i run git clone https://github.com/tnfe/FFCreator.git in /root
edit package.jason add a line "start": "node /root/FFCreator/lib/node/node.js"
then run "xvfb-run -s "-ac -screen 0 800x600x24" npm start"

**Comment by drawcall** [comment]
`node /root/FFCreator/lib/node/node.js` 
It is wrong to execute this entry, please check the document carefully
