### ISSUE TITLE
display.getAttr() is not a function

### ISSUE THREAD

**Issue by jianshuo** [tnfe/FFCreator#160]
<img width="805" alt="Screen Shot 2021-12-15 at 10 42 35 PM" src="https://user-images.githubusercontent.com/2012831/146209860-c420b674-3d46-4669-a0c7-9fe0fe3a0658.png">

At line 132 of file ffcreator/lib/animate/animate.js,
when `key` in `from` is not found in `to`,  `display.getAttr()` is called.

However, after migrating to InkPaint, display object no longer has getAttr() function.

This causes few animation break, such as moveingInLeft ...

Suggest to either add the function, or just use the following:
to[key] = display[key]

**Comment by drawcall** [comment]
InkPaint DisplayObject has getAttr method
