### ISSUE TITLE
在centos上生成gif组件的时候出现报错

### ISSUE THREAD

**Issue by zwgdrs** [tnfe/FFCreator#161]
在centos上生成gif组件的时候出现如下问题：
```javascript
[FF] FFGif Gif preProcessing errorffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error
frame=   17 fps=5.0 q=-0.0 Lsize=N/A time=00:00:00.30 bitrate=N/A dup=16 drop=0 speed=0.0875x
video:965kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

FFCreator error: [object Object]
[FF] Creator production error. FFEvent {
  type: 'error',
  pos: 'preProcessing',
  error: 'ffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error\n' +
    'frame=   17 fps=5.0 q=-0.0 Lsize=N/A time=00:00:00.30 bitrate=N/A dup=16 drop=0 speed=0.0875x    \n' +
    'video:965kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown\n' +
    'Conversion failed!\n'
}
this.time 1639651409128
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg was killed with signal SIGKILL
    at ChildProcess.<anonymous> (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:375:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:170:11)
    at Socket.<anonymous> (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:197:11)
    at Socket.emit (events.js:387:35)
    at Pipe.<anonymous> (net.js:675:12)
```

**Comment by zwgdrs** [comment]
补充一下，在mac上是ok的。centos上ffmpeg版本是
```
ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 8 (GCC)
configuration: --arch=x86_64 --bindir=/usr/bin --datadir=/usr/share/ffmpeg --disable-debug --disable-static --disable-stripping --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-alsa --enable-bzlib --enable-chromaprint --enable-decklink --enable-frei0r --enable-gcrypt --enable-gmp --enable-gnutls --enable-gpl --enable-gray --enable-iconv --enable-ladspa --enable-libass --enable-libaom --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdc1394 --enable-libdav1d --enable-libdavs2 --enable-libdrm --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libiec61883 --enable-libilbc --enable-libjack --enable-libkvazaar --enable-liblensfun --enable-libmodplug --enable-libmp3lame --enable-libndi_newtek --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-librtmp --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxcb --enable-libxcb-shape --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-lzma --enable-nonfree --enable-openal --enable-opencl --enable-opengl --enable-postproc --enable-sdl2 --enable-shared --enable-swresample --enable-swscale --enable-vaapi --enable-version3 --enable-vdpau --enable-xlib --enable-zlib --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --prefix=/usr --shlibdir=/usr/lib64 --enable-libzmq --enable-vapoursynth --enable-cuda --enable-cuvid --enable-ffnvcodec --enable-libmfx --enable-libnpp --enable-libsvtav1 --enable-libsvthevc --enable-libsvtvp9 --enable-libvmaf --enable-nvdec --enable-nvenc --extra-cflags=-I/usr/include/cuda --cpu=x86_64
```

**Comment by zwgdrs** [comment]
补充
```javascript
地址 https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/fa54b639-ff40-4a30-95dc-c1f54a6ee950.gif
{
  path: 'https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/fa54b639-ff40-4a30-95dc-c1f54a6ee950.gif',
  uri: '/www/cosfs/videoserver/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/fa54b639-ff40-4a30-95dc-c1f54a6ee950.gif',
  anchor: 0.5,
  pos: { x: 360, y: 640 },
  size: { width: 1016, height: 406 },
  effectList: [ { name: 'fadeIn', time: 0, delay: 0 } ]
}
地址 https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/6201f85c-3c95-4132-bf56-f0b81c696bf5.gif
{
  path: 'https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/6201f85c-3c95-4132-bf56-f0b81c696bf5.gif',
  uri: '/www/cosfs/videoserver/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/6201f85c-3c95-4132-bf56-f0b81c696bf5.gif',
  anchor: 0.5,
  pos: { x: 360, y: 640 },
  size: { width: 720, height: 720 },
  effectList: [ { name: 'fadeIn', time: 0, delay: 0 } ]
}
地址 https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif
{
  path: 'https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif',
  uri: '/www/cosfs/videoserver/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif',
  anchor: 0.5,
  pos: { x: 360, y: 640 },
  size: { width: 2290, height: 406 },
  effectList: [ { name: 'fadeIn', time: 0, delay: 0 } ]
}
制作场景后
[FF] FFGif Gif preProcessing errorffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error
frame=   17 fps=6.3 q=-0.0 Lsize=N/A time=00:00:00.30 bitrate=N/A dup=16 drop=0 speed=0.112x
video:965kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

FFCreator error: [object Object]
[FF] Creator production error. FFEvent {
  type: 'error',
  pos: 'preProcessing',
  error: 'ffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error\n' +
    'frame=   17 fps=6.3 q=-0.0 Lsize=N/A time=00:00:00.30 bitrate=N/A dup=16 drop=0 speed=0.112x    \n' +
    'video:965kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown\n' +
    'Conversion failed!\n'
}
App render eror:: TypeError: this.children[i].renderCanvas is not a function
App render eror:: TypeError: this.children[i].renderCanvas is not a function
App render eror:: TypeError: this.children[i].renderCanvas is not a function
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg was killed with signal SIGKILL
    at ChildProcess.<anonymous> (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:375:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:170:11)
    at ChildProcess.<anonymous> (/www/wwwroot/ai-generation-video/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:180:11)
    at ChildProcess.emit (events.js:375:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

**Comment by penghui** [comment]
升级一下ffmpeg到4.4试试？看上应该去不是ffcreator的问题。
可以直接使用下面命令尝试，这是类似ffcreator底层调用ffmpeg的：
```Bash
ffmpeg -i https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif %d.jpg
```

**Comment by zwgdrs** [comment]
> 升级一下ffmpeg到4.4试试？看上应该去不是ffcreator的问题。 可以直接使用下面命令尝试，这类似ffcreator底层调用ffmpeg的命令：
> 
> ```shell
> ffmpeg -i https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif -vsync cfr -r 30 -start_number 0 %d.jpg
> ```

已经升级，但是仍然有问题，感觉是因为%d没有被centos和Ubuntu系统正常处理导致的，但是我也没有找到应该如何替换的方法

**Comment by penghui** [comment]
我这边ubuntu18.04 ffmpeg 4.3.2测试下来是可以的:
```
ubuntu@VM-0-12-ubuntu:~/temp$ ffmpeg -i https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif -vsync cfr -r 30 -start_number 0 %d.jpg
ffmpeg version 4.3.2-0york0~18.04 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, gif, from 'https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif':
  Duration: 00:00:00.26, start: 0.000000, bitrate: 343 kb/s
    Stream #0:0: Video: gif, bgra, 1076x191, 100 tbr, 100 tbn, 100 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (gif (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x563494ef2880] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '%d.jpg':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: mjpeg, yuvj444p(pc), 1076x191, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.91.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame=    8 fps=0.0 q=12.0 Lsize=N/A time=00:00:00.26 bitrate=N/A dup=6 drop=0 speed=1.23x
video:124kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ubuntu@VM-0-12-ubuntu:~/temp$ ls
0.jpg  1.jpg  2.jpg  3.jpg  4.jpg  5.jpg  6.jpg  7.jpg
ubuntu@VM-0-12-ubuntu:~/temp$
```

**Comment by zwgdrs** [comment]
> 我这边ubuntu18.04 ffmpeg 4.3.2测试下来是可以的:
> 
> ```
> ubuntu@VM-0-12-ubuntu:~/temp$ ffmpeg -i https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif -vsync cfr -r 30 -start_number 0 %d.jpg
> ffmpeg version 4.3.2-0york0~18.04 Copyright (c) 2000-2021 the FFmpeg developers
>   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
>   configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
>   libavutil      56. 51.100 / 56. 51.100
>   libavcodec     58. 91.100 / 58. 91.100
>   libavformat    58. 45.100 / 58. 45.100
>   libavdevice    58. 10.100 / 58. 10.100
>   libavfilter     7. 85.100 /  7. 85.100
>   libavresample   4.  0.  0 /  4.  0.  0
>   libswscale      5.  7.100 /  5.  7.100
>   libswresample   3.  7.100 /  3.  7.100
>   libpostproc    55.  7.100 / 55.  7.100
> Input #0, gif, from 'https://videoserver-1253854551.cos.ap-beijing.myqcloud.com/bfdd18e7-d4e2-4b61-b0de-9a8a766dda26/img/85bcc407-ab36-4031-a653-94521868cf59.gif':
>   Duration: 00:00:00.26, start: 0.000000, bitrate: 343 kb/s
>     Stream #0:0: Video: gif, bgra, 1076x191, 100 tbr, 100 tbn, 100 tbc
> Stream mapping:
>   Stream #0:0 -> #0:0 (gif (native) -> mjpeg (native))
> Press [q] to stop, [?] for help
> [swscaler @ 0x563494ef2880] deprecated pixel format used, make sure you did set range correctly
> Output #0, image2, to '%d.jpg':
>   Metadata:
>     encoder         : Lavf58.45.100
>     Stream #0:0: Video: mjpeg, yuvj444p(pc), 1076x191, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
>     Metadata:
>       encoder         : Lavc58.91.100 mjpeg
>     Side data:
>       cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
> frame=    8 fps=0.0 q=12.0 Lsize=N/A time=00:00:00.26 bitrate=N/A dup=6 drop=0 speed=1.23x
> video:124kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> ubuntu@VM-0-12-ubuntu:~/temp$ ls
> 0.jpg  1.jpg  2.jpg  3.jpg  4.jpg  5.jpg  6.jpg  7.jpg
> ubuntu@VM-0-12-ubuntu:~/temp$
> ```

谢谢，我解决了这个问题，主要是因为我创建视频的时候output和cache写的路径每次都是一个uuid生成的随机地址，然后我改为一个固定地址就没有这个问题了，但是我确实也不清楚为什么会有这个问题

**Comment by xeoshow** [comment]
遇到了同样问题。我是output需要每次不同，不能固定同一个。这种情况哪位大神知道需要如何解决呢？谢谢。
![image](https://user-images.githubusercontent.com/1164284/193397941-fb3c1a56-5d31-4046-a22b-f924fdcf9159.png)
0|worker  | 2022-10-01 15:10:44: createFFTask.FFCreator start
0|worker  | 2022-10-01 15:10:44: [FF] FFGif Gif preProcessing errorffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error
0|worker  | frame=    3 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.06 bitrate=N/A speed=15.1x
0|worker  | video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
0|worker  | Conversion failed!
0|worker  |
0|worker  | 2022-10-01 15:10:44: createFFTask.FFCreator error: ffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error
0|worker  | frame=    3 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.06 bitrate=N/A speed=15.1x
0|worker  | video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
0|worker  | Conversion failed!
0|worker  | 2022-10-01 15:10:44: [FF] Creator production error. FFEvent {
0|worker  |   type: 'error',
0|worker  |   pos: 'preProcessing',
0|worker  |   error: 'ffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error\n' +
0|worker  |     'frame=    3 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.06 bitrate=N/A speed=15.1x    \n' +
0|worker  |     'video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown\n' +
0|worker  |     'Conversion failed!\n'
0|worker  | }
0|worker  | 2022-10-01 15:10:44: Error: Image given has not completed loading
0|worker  |     at Function.convertToImageData (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+inkpaint@2.7.2/node_modules/inkpaint/lib/polyfill/Image.js:54:9)
0|worker  |     at BaseTexture.adaptedNodeCanvas (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+inkpaint@2.7.2/node_modules/inkpaint/lib/textures/BaseTexture.js:145:36)
0|worker  |     at Texture.updateSource (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+inkpaint@2.7.2/node_modules/inkpaint/lib/textures/Texture.js:108:24)
0|worker  |     at Sprite.updateBaseTexture (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+inkpaint@2.7.2/node_modules/inkpaint/lib/sprites/Sprite.js:188:18)
0|worker  |     at FFGifImage.drawing (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.5/node_modules/ffcreator/lib/node/gif.js:171:18)
0|worker  |     at /mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.5/node_modules/ffcreator/lib/timeline/update.js:38:29
0|worker  |     at arrayEach (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+lodash@4.17.21/node_modules/lodash/_arrayEach.js:15:9)
0|worker  |     at forEach (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+lodash@4.17.21/node_modules/lodash/forEach.js:38:10)
0|worker  |     at Object.update (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.5/node_modules/ffcreator/lib/timeline/update.js:38:5)
0|worker  |     at Timeline.nextFrame (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.5/node_modules/ffcreator/lib/timeline/timeline.js:183:22)
0|worker  | Error: ffmpeg was killed with signal SIGKILL
0|worker  |     at ChildProcess.<anonymous> (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+fluent-ffmpeg@2.1.2/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
0|worker  |     at ChildProcess.emit (events.js:315:20)
0|worker  |     at ChildProcess.EventEmitter.emit (domain.js:467:12)
0|worker  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
PM2       | App name:worker id:0 disconnected
PM2       | App [worker:0] exited with code [7] via signal [SIGINT]
PM2       | App [worker:0] starting in -cluster mode-
PM2       | App [worker:0] online

**Comment by wth1107** [comment]
@xeoshow 您好 您解决了吗
