### ISSUE TITLE
可以在一个场景下面设置某个元素在指定时间之后消失么

### ISSUE THREAD

**Issue by linqian02** [tnfe/FFCreator#166]
比如某个场景的duration为7秒，里面有一张图片，从1秒开始(这个可以使用动画完成)，到5秒就消失，消失该如何实现么？FFCreator支持么

**Comment by drawcall** [comment]
obj.addEffect(['fadeOut'], 2, 4);

**Comment by linqian02** [comment]
> obj.addEffect(['fadeOut'], 2, 4);

@drawcall  明白了，感谢！
