### ISSUE TITLE
ffcreator 基础demo 运行出错

### ISSUE THREAD

**Issue by mcl0626** [tnfe/FFCreator#170]
环境：centos7  ffmpeg4.1  node14.18.3
按官网教程一步步安装了所需依赖 插件 
执行 xvfb-run -s "-ac -screen 0 1280x1024x24" node examples/index.js 8088
![image](https://user-images.githubusercontent.com/47437722/149603565-fcbf7574-2f14-47e3-84cc-dd6b89424e2a.png)
望各位大神 指点迷津 ！ 只想完整的运行这个  基础demo

**Comment by zjqiudan** [comment]
楼主可以加我qq15233913 一起研究 也碰到了环境装好无法运行demo的问题了

**Comment by DZwangbing** [comment]
demo好像都运行不起来，只能参考demo实现功能

**Comment by drawcall** [comment]
@mcl0626 
https://github.com/tnfe/FFCreator/issues/58
https://stackoverflow.com/questions/20035338/ffmpeg-on-heroku-unrecognized-option-preset

**Comment by drawcall** [comment]
@DZwangbing 
please upload your error

**Comment by javaswing** [comment]
尝试下这个：`xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24+32" node examples/index.js 8088`

**Comment by mcl0626** [comment]
http://www.manks.top/ffmpeg-install-linux-centos.html  按此教程重新编译安装ffmpeg后  即可正常运行 demo
