### ISSUE TITLE
可以集成fabric.js吗，当前自定义样式能力偏弱

### ISSUE THREAD

**Issue by changqing91** [tnfe/FFCreator#172]

**Comment by drawcall** [comment]
You can use the FFExtras class to extend, it is actually very powerful

**Comment by yeeddd** [comment]
> You can use the FFExtras class to extend, it is actually very powerful

老哥，能介绍下，怎么用这个类来做扩展吗？目前想要用最新的lottie-web库。使用jsdom和node-canvas已经能导出每一帧的图片了，在研究怎么把这个与FFCreator结合起来。

**Comment by drawcall** [comment]
mark
