### ISSUE TITLE
请问FFCreator有增加滤镜特效的计划嘛？

### ISSUE THREAD

**Issue by DZwangbing** [tnfe/FFCreator#174]
非常感谢您的团队所带来的开源工程，为我提供了很大的帮助👍

请问FFCreator后续有增加滤镜特效的计划嘛？

**Comment by drawcall** [comment]
Oh I may consider adding in the future

**Comment by 121786404** [comment]
滤镜确实很需要，等待

**Comment by drawcall** [comment]
Configuration settings:
render: "gl"

Use setBulr to set the blur filter, currently only supports blur

**Comment by kxxoling** [comment]
@drawcall Is it any way to support blur in canvas mode?

**Comment by drawcall** [comment]
Oh, add later
