### ISSUE TITLE
TypeError: Cannot read property 'ARRAY_BUFFER' of null

### ISSUE THREAD

**Issue by armandoarmando** [tnfe/FFCreator#175]
Hello guys! I'm trying to create a video in Ubuntu 18 and I receive this error:

`node:1725653) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ARRAY_BUFFER' of null
13|    at FFTransition.createBuffer (/var/www/project.video/node_modules/ffcreator/lib/animate/transition.js:73:45)
`
I already did it:

![image](https://user-images.githubusercontent.com/46790753/152199802-de4c3a21-1978-4fa0-ac74-23547ed88b30.png)

I saw the same issue here https://github.com/tnfe/FFCreator/issues/136
what do u mean with delete the cache @drawcall?

Someone else has the same problem?

Many thanks!
Armando

**Comment by drawcall** [comment]
xvfb-run -s "-ac -screen 0 1280x1024x24" npm start

**Comment by armandoarmando** [comment]
Now works! thanks!
I was running this command:

`xvfb-run -s "-ac -screen 0 1280x1024x24" pm2 start yarn --name 'project' -- start`

Can u explain to me why didn't work? @drawcall 

Thanks!

**Comment by armandoarmando** [comment]
@drawcall I found the solution https://github.com/segmentio/nightmare/issues/224#issuecomment-239335488

thanks!

**Comment by drawcall** [comment]
```
{
  "apps" : [{
    "name"        : "<your_app_name>",
    "script"      : "<your_main.js>",
    "env": {
      "DISPLAY": ":99"
    }
  },
    {
      "name"        : "Xvfb",
      "interpreter" : "none",
      "script"      : "Xvfb",
      "args"        : ":99"
    }]
}
```
pm2 start process.json
