### ISSUE TITLE
当使用WebGL渲染器时渲染耗时比Canvas渲染器更长

### ISSUE THREAD

**Issue by Vinlic** [tnfe/FFCreator#176]
当useGL为true时，我们发现WebGL渲染器虽然利用了GPU，但渲染耗时是Canvas渲染器的两倍，这似乎有点奇怪？
我们在Node.js中使用FFCreator

**Comment by drawcall** [comment]
Oh, because it is not webgl, but the gl simulated by mesa3d. However, there is still room for further optimization
