### ISSUE TITLE
如何让视频元素完整的填充整个画布，即使视频元素被拉伸来看不清楚

### ISSUE THREAD

**Issue by linqian02** [tnfe/FFCreator#178]
如题，我尝试着将视频元素的宽高设置为画布的宽高，这样不会导致视频元素拉伸，只会对视频元素对截断处理。
怎么样才能实现类似cover覆盖完全的效果?

**Comment by drawcall** [comment]
Non-proportional scaling?

**Comment by linqian02** [comment]
> 



> Non-proportional scaling?
是的，我想表达的就是这个意思[笑哭]

**Comment by isabirahmed** [comment]
@linqian02 : Did you find a solution for this?

**Comment by linqian02** [comment]
> @linqian02 : Did you find a solution for this?

@isabirahmed   [editly](https://github.com/mifi/editly)
