### ISSUE TITLE
how can I use FFExtras?

### ISSUE THREAD

**Issue by Acouse** [tnfe/FFCreator#180]
Hi,  I want use fabric.js.  It seems that FFExtras can be used.
But I can't find it in the docs.  Are there any examples？
Thanks

**Comment by drawcall** [comment]
/**
 * FFExtras - A component that can be expanded freely
 *
 * ####Example:
 *
 *     const extras = new FFExtras();
 *     extras.init = function(InkPaint){ ... }
 *     extras.update = function(InkPaint){ ... }
 *     extras.destroyed = function(InkPaint){ ... }
 *     scene.addChild(extras);
 */

InkPaint is a lightweight node.js canvas graphics animation library. It forks from the famous canvas engine pixi.js. You can use it to do server-side image synthesis.


https://github.com/drawcall/inkpaint
