### ISSUE TITLE
中文显示成unicode编码

### ISSUE THREAD

**Issue by mkzxcvbnm** [tnfe/FFCreator#184]
![image](https://user-images.githubusercontent.com/16659155/155255024-2da3569e-0040-4b90-a59f-74c6b46b88c7.png)
![image](https://user-images.githubusercontent.com/16659155/155255072-16a7f012-ccc8-456d-932d-05f0dcf79034.png)
中文显示成unicode编码

我在本地电脑上编译是正常的 哪里设置的问题?

**Comment by drawcall** [comment]
使用TrueType格式字体

**Comment by mkzxcvbnm** [comment]
> 使用 TrueType 字体

谢谢 我没有设置字体 在服务器上必须设置一个字体 本地貌似可以不设置
