### ISSUE TITLE
想了解一下是否可以直接改用pixi.js而不是inkpaint

### ISSUE THREAD

**Issue by milkliker** [tnfe/FFCreator#189]
因为pixi.js有更完善的社区和周边插件支持，可以补齐很多效果。
但inkpaint确实改动非常大，比如引入了scale来实现动画。
所以想请教一下作者，目前有哪些是pixi.js不满足的地方？

**Comment by drawcall** [comment]
The APIs of inkpaint and pixi are almost the same, and the animation method is different from FFCreator

**Comment by milkliker** [comment]
> The APIs of inkpaint and pixi are almost the same, and the animation method is different from FFCreator

Got! thanks

**Comment by nipoop** [comment]
hi, i have the same question, could you explain more about this? why FFcreator use inkpaint without pixijs

**Comment by drawcall** [comment]
> hi, i have the same question, could you explain more about this? why FFcreator use inkpaint without pixijs

Theoretically, it is possible. Inkpaint is developed based on a version of pixi, with many modifications made to accommodate rendering in the nodejs mode.
