### ISSUE TITLE
The transition is invalid and the screen is black ?

### ISSUE THREAD

**Issue by zhuqiaolun** [tnfe/FFCreator#19]
`        const scene1 = new FFScene();
        scene1.setTransition('Colorful', 1.5,{});
        scene1.setDuration(5);
        creator.addChild(scene1);`

**Comment by drawcall** [comment]
Because there are no elements in your scene, you can't see anything

**Comment by zhuqiaolun** [comment]
> Because there are no elements in your scene, you can't see anything

`
const creatScene = ({index, transition, text}) => {
  const scene = new FFScene();
  scene.setBgColor('#3b3a98');
  scene.setDuration(5);
  scene.setTransition(transition, 1,{});

  // bg img
  const img = path.join(__dirname, `./assets/imgs/trans/0${index}.jpeg`);
  const bg = new FFImage({path: img, resetXY: true});
  scene.addChild(bg);

  // title text
  const ftext = new FFText({text, x: width / 2, y: height / 2 + 50, fontSize: 38});
  ftext.setColor('#30336b');
  ftext.alignCenter();
  ftext.setBackgroundColor('#ffffff');
  ftext.addEffect('fadeInRight', 1, 1.3);
  ftext.setStyle({padding: [4, 12, 6, 12]});
  scene.addChild(ftext);

  // add logo2
  const logo = index === 1 ? logo2 : logo1;
  const flogo = new FFImage({path: logo, x: width / 2, y: height / 2 - 100});
  flogo.setScale(0.6);
  flogo.addEffect('fadeInLeft', 1, 1);
  scene.addChild(flogo);

  return scene;
};
`
https://github.com/tnfe/FFCreator/blob/master/examples/transition.js
https://tnfe.github.io/FFCreator/_media/imgs/ani.gif
When the scene【Colorful】 is switched, it shows black。

**Comment by fantasticsoul** [comment]
I have try your code in windows env, everything is ok.
