### ISSUE TITLE
如何调整每条字幕的切换速度

### ISSUE THREAD

**Issue by mcl0626** [tnfe/FFCreator#191]
现在遇到一个问题，想给背景音乐配字幕，然后使用FFSubtitle ，设置setText为背景音乐的中文，并使用setDuration设置字幕时长为背景音乐时长，此时出现问题，我的背景音乐为58秒，设置FFSubtitle.setDuration(58),结果字幕在51秒时已播放完毕。后边的7秒都停留在最后一条字幕上。该怎么解决呢？经过我不断尝试，最终FFSubtitle.setDuration(65)时，字幕和背景音乐正好对应。有更好的方法吗？

**Comment by drawcall** [comment]
I'm swamped #mark
