### ISSUE TITLE
如何设置字幕背景色为透明

### ISSUE THREAD

**Issue by mcl0626** [tnfe/FFCreator#193]
我不想要字幕带有背景色该怎么设置呢

**Comment by drawcall** [comment]
use `setBackgroundColor`

**Comment by mcl0626** [comment]
> use `setBackgroundColor`
参数该咋写呢？ setBackgroundColor:none?我想设置为没有背景色的咋设置呢，

**Comment by C1oudust** [comment]
backgroundColor: 'transparent'

**Comment by mcl0626** [comment]
> backgroundColor: 'transparent'

thankyou very much ,your answer is very 给力
