### ISSUE TITLE
win7上跑切换scene的时候会黑屏1秒

### ISSUE THREAD

**Issue by gclsoft** [tnfe/FFCreator#2]
![image](https://user-images.githubusercontent.com/1269898/99150683-2f637680-26d1-11eb-9288-5dc15ff4ba19.png)
node:v11.10.1
os: win7
version: 源码编译的example
ffmpeg version 4.3.1-2020-10-01-full_build

**Comment by drawcall** [comment]
You can upgrade to v1.3.1 and try again, if it still doesn’t work, please check if there is any error message.

In x86 system `d3dcompiler_47.dll` should be in c:\windows\system32, but if isn't then you can find another copy in the deps/ folder. 
[https://github.com/stackgl/headless-gl/tree/master/deps/windows/dll/x64](https://github.com/stackgl/headless-gl/tree/master/deps/windows/dll/x64)

**Comment by gclsoft** [comment]
update gl solved the problem

**Comment by drawcall** [comment]
> update gl solved the problem

Oh thanks, if you like this library, please help promote it

**Comment by kumarboo** [comment]
> update gl solved the problem



> update gl solved the problem

It has been upgraded to 4.9.0, but the problem still exists.

**Comment by fantasticsoul** [comment]
> > update gl solved the problem
> 
> > update gl solved the problem
> 
> It has been upgraded to 4.9.0, but the problem still exists.
> 
> > scene.setTransition ('cube ', 0) is OK, but the transition effect is invalid

upgrade ffcreator to lastest version
