### ISSUE TITLE
为什么无法进行npm start？显示缺少脚本？

### ISSUE THREAD

**Issue by Amanda2020619** [tnfe/FFCreator#20]
![image](https://user-images.githubusercontent.com/68992199/101902865-4f158e00-3bee-11eb-8c4c-8ff44a8678b1.png)
使用cmd进行npm start总是报错，后来用powershell在安装目录下打开，运行npm run examples可以成功合成案例视频，但是无法显示进行自己成功开始新的视频编辑。。。
想知道如何解决该问题？
希望官方能出一个详细的安装到成功使用的教程，我已经很认真的根据你们出的使用文档安装依赖和配置环境了，还是不成功，最后花钱去淘宝找了外援程序员，他也是只能给进行跑到案例合成这一步。我们目前的业务非常需要使用FFCreator来进行测试效果，但这对新手来说确实有点难度。希望教程能再详细一点，感谢！

**Comment by drawcall** [comment]
Oh, the git repository is the package source code and there is no start entry. `npm run examples` is the default demo provided. I think you should learn some knowledge about node.js.
