### ISSUE TITLE
video created in my localhost server but not working in public server.  got warning message

### ISSUE THREAD

**Issue by balajisv** [tnfe/FFCreator#201]
(node:4986) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ARRAY_BUFFER' of null
    at FFTransition.createBuffer (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/animate/transition.js:73:45)
    at FFTransition.createTransition (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/animate/transition.js:61:10)
    at FFTransition.bindGL (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/animate/transition.js:40:10)
    at /var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/core/renderer.js:119:57
    at arrayEach (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/node_modules/lodash/forEach.js:38:10)
    at Renderer.transBindGL (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/core/renderer.js:119:5)
    at Renderer.start (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/core/renderer.js:55:10)
(node:4986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by drawcall** [comment]
xvfb-run -s "-ac -screen 0 1280x1024x24" npm start

**Comment by balajisv** [comment]
> xvfb-run -s "-ac -screen 0 1280x1024x24" npm start

how to start this using pm2 ?

**Comment by balajisv** [comment]
xvfb-run -s "-ac -screen 0 1280x1024x24" pm2 start npm --name 'juan' -- start

>> i used this command but its not working !

**Comment by mcl0626** [comment]
> xvfb-run -s "-ac -screen 0 1280x1024x24" pm2 start npm --name 'juan' -- start
> 
> > > i used this command but its not working !

https://github.com/segmentio/nightmare/issues/224#issuecomment-239335488
Maybe this will help you

**Comment by drawcall** [comment]
```
{
  "apps" : [{
    "name"        : "<your_app_name>",
    "script"      : "<your_main.js>",
    "env": {
      "DISPLAY": ":99"
    }
  },
    {
      "name"        : "Xvfb",
      "interpreter" : "none",
      "script"      : "Xvfb",
      "args"        : ":99"
    }]
}
```
pm2 start process.json

**Comment by balajisv** [comment]
> pm2 start process.json

sorry.. Same error occurs.. 

32|juan  | TypeError: Cannot read property 'ARRAY_BUFFER' of null
32|juan  |     at FFTransition.createBuffer (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/animate/transition.js:73:45)
32|juan  |     at FFTransition.createTransition (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/animate/transition.js:61:10)
32|juan  |     at FFTransition.bindGL (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/animate/transition.js:40:10)
32|juan  |     at /var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/core/renderer.js:119:57
32|juan  |     at arrayEach (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/node_modules/lodash/_arrayEach.js:15:9)
32|juan  |     at forEach (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/node_modules/lodash/forEach.js:38:10)
32|juan  |     at Renderer.transBindGL (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/core/renderer.js:119:5)
32|juan  |     at Renderer.start (/var/www/html/juan_fundoo/public/APP/node_modules/ffcreator/lib/core/renderer.js:55:10)

**Comment by balajisv** [comment]
could you please suggest a solution or shall i start this using npm forever?

**Comment by balajisv** [comment]
how to start using npm forever?

**Comment by drawcall** [comment]
```javascript
{
  "apps" : [{
    "name"        : "<your_app_name>",
    "script"      : "<your_main.js>",
    "env": {
      "DISPLAY": ":99"
    }
  },
    {
      "name"        : "Xvfb",
      "interpreter" : "none",
      "script"      : "Xvfb",
      "args"        : ":99 -ac -screen 0 1280x1024x24"
    }]
}
```
