### ISSUE TITLE
FFCreatorLite不支持混合模式吗?

### ISSUE THREAD

**Issue by z411500976** [tnfe/FFCreator#209]
fvideo1.addBlend('screen');
报错了Error: ffmpeg exited with code 1: Cannot find a matching stream for unlabeled input pad 1 on filter Parsed_blend_10

**Comment by drawcall** [comment]
support, please check your code

**Comment by z411500976** [comment]
![QQ截图20220413170514](https://user-images.githubusercontent.com/24216715/163141278-c6a04e73-e5a9-4013-8c24-c8cc5c7202b9.png)
videoBg.addBlend('screen'); FFCreator 是没有问题的，使用方式不对吗？我对ffmpeg命令行不熟悉。

**Comment by z411500976** [comment]
> support, please check your code

The latest version 2.3.8 used by FFCreatorLite

**Comment by drawcall** [comment]
Please submit ffcreatlite issues here
https://github.com/drawcall/FFCreatorLite/issues
