### ISSUE TITLE
你好，视频看上去似乎不太清晰

### ISSUE THREAD

**Issue by w5w6** [tnfe/FFCreator#21]
https://user-images.githubusercontent.com/68835949/102597299-6821c000-4155-11eb-9c5c-bb1684a4ff0e.mp4

文字和图片，都似乎不太清晰的感觉

**Comment by drawcall** [comment]
Oh, I think your video is clear enough. If you want to improve the picture quality, you can set parameters such as `crf`, `vb`, `preset` (you can consult the ffmpeg documentation).
```
const creator = new FFCreator({
     cacheDir,
     crf
     vb
     preset
```

Remember to download the latest version of ffcreator

**Comment by w5w6** [comment]
@drawcall  很抱歉，我的英文不太好，只能回复中文

我将crf更改为1后，视频给我的感觉还是不太好

特别是文字 ，跟html里的效果差别很大。

1、浏览器里制作布局时候的效果
![WX20201221-153046](https://user-images.githubusercontent.com/68835949/102750828-854ace80-43a1-11eb-894f-55aa4da95b74.png)

2、生成后的效果，crf设置为1了
https://user-images.githubusercontent.com/68835949/102750798-6f3d0e00-43a1-11eb-9e55-a5b873af20fc.mp4

**Comment by fantasticsoul** [comment]
你好，看了你提供的链接，感觉很清晰了啊

**Comment by w5w6** [comment]
> 你好，看了你提供的链接，感觉很清晰了啊

其实不清晰的，谢谢你的回复，等我过年回老家再好好看看着，先close了
