### ISSUE TITLE
Having issue setting up multiple Scenes

### ISSUE THREAD

**Issue by chukwumaijem** [tnfe/FFCreator#213]
Hi, I have an application that involves creating multiple scenes within a loop, but only one scene gets created successfully. Any more than that i start getting all sorts of errors. From width of undefined to segmentation dump error. I setup my own queue using `bull` so only one video is ever processed at a time.

Here is a screenshot of the error.
![Screenshot from 2022-04-16 13-32-13](https://user-images.githubusercontent.com/17248267/163675493-cca4e17e-7a34-4762-aef6-78dddbf70a7d.png)

![Screenshot from 2022-04-16 13-32-41](https://user-images.githubusercontent.com/17248267/163675495-860a8d6b-369c-41b0-bb24-9d8b3cbfe00e.png)

Here is my code.

```
    const image = new FFImage({
      path: imagePath,
      opacity: 1,
      y: this.canvasHeight / 2,
      x: 500,
      scale: 0.9,
    });

    for (let i = 0; i < textArray.length; i++) {
      const textLine = textArray[i];
      const duration = 10;
      const fontSize = this.fontSize;
      const renderText = new FFText({
        text: textLine,
        style: { fontSize },
        x: 900,
        y: this.canvasHeight / 2,
      });
      renderText.setColor('#ffffff');
      renderText.addEffect('fadeIn', 1, 1);
      renderText.addEffect('fadeOut', 3, duration - 3);
      renderText.setFont(path.join(this.assetPath, `fonts/${this.font}`));

      renderText.setAnchor(0, 0.5);
      renderText.setStyle({ verticalAlign: 'middle' });

      const scene = new FFScene();
      scene.setBgColor(this.sceneColor);
      scene.setDuration(duration);
      this.creator.addChild(scene);

      scene.addChild(image);
      scene.addChild(renderText);
    }
```

**Comment by chukwumaijem** [comment]
The video builds in the end, but Image is not rendered on the scenes. Only text shows up.

**Comment by drawcall** [comment]
I run your code without errors.

Please ensure that the path of the image is correct, and do not addChild image in the for loop

**Comment by drawcall** [comment]
Maybe you can provide more detailed code or upload the project

**Comment by chukwumaijem** [comment]
You mean I shouldn't do scene.addChild(image) within the loop? But I want the image to appear in all the scenes. How do I do that?

**Comment by drawcall** [comment]
> You mean I shouldn't do scene.addChild(image) within the loop? But I want the image to appear in all the scenes. How do I do that?

![image](https://user-images.githubusercontent.com/3407208/163694950-df4c8030-40c9-4bcf-9bea-02ee03a7e77a.png)
But you created it once

**Comment by chukwumaijem** [comment]
Yes, I did. I thought the optimal thing to do was to create it once and reuse it wherever it was needed. Will try creating it within the loop and see what I get.

**Comment by chukwumaijem** [comment]
Thank you @drawcall, that worked!
