### ISSUE TITLE
stderr:undefinedCannot find ffmpeg

### ISSUE THREAD

**Issue by jusheng** [tnfe/FFCreator#22]
FFCreator error: Cannot find ffmpeg
[FF] Creator production error. [object Object]
[FF] Synthesis stdout:undefined 
 stderr:undefinedCannot find ffmpeg

**Comment by drawcall** [comment]
FFCreator depends on FFmpeg>=0.9 and above. Please set FFmpeg as a global variable, otherwise you need to use setFFmpegPath to add FFmpeg native path.

```
FFCreator.setFFmpegPath('...');
```
