### ISSUE TITLE
插入视频节点，合成mp4视频，偶现只有音频轨道，没有视频轨道，日志看video.js里报错，can‘t read updateBaseTexture of undefined

### ISSUE THREAD

**Issue by lyz1991** [tnfe/FFCreator#222]
ffmpeg查看合成出来视频，只有音频轨道没有视频轨道

**Comment by drawcall** [comment]
素材中有网络图片吗

**Comment by lyz1991** [comment]
> 素材中有网络图片吗

每次复现素材不一致，有的有网络图片，有的没素材，就插入一个网络音频audio节点，然后合成出来也是只有音频轨道的mp4文件

**Comment by lyz1991** [comment]
@drawcall 这个问题还有的救吗？

**Comment by lyz1991** [comment]
> 素材中有网络图片吗

这个问题还有的救吗

**Comment by drawcall** [comment]
可能是中间遇到错误导致ffvideo destroy，需要捕获下具体报错。制作视频可以使用ffcreatorlite

**Comment by drawcall** [comment]
use defaultOutputOptions

**Comment by lyz1991** [comment]
> use defaultOutputOptions

从目前信息上看，是video里的this.display是个undefined

**Comment by lyz1991** [comment]
> 可能是中间遇到错误导致ffvideo destroy，需要捕获下具体报错。制作视频可以使用ffcreatorlite。能否上传相关项目？或者在源代码中调试。

从目前信息上看，是video里的this.display是个undefined

**Comment by lyz1991** [comment]
> baseline -level 3.1

像ffmpeg -i .\843686411830960128.mp4 -vcodec libx264 -profile:v baseline -level 3.1 -preset:v medium -acodec aac -ar 48000 -ac 1 11.mp4这个命令， defaultOutputOptions应该怎么设置呢？

**Comment by lyz1991** [comment]
> -profile:v

因为我看到代码里编码格式main好像写死的，      .concat([
        '-c:v',
        'libx264', // c:v - H.264
        '-profile:v',
        'main', // profile:v - main profile: mainstream image quality. Provide I / P / B frames
        '-preset',
        preset, // preset - compromised encoding speed
        '-movflags',
        'faststart',
        '-pix_fmt',
        'yuv420p',
        '-r',
        fps,
      ]);

**Comment by drawcall** [comment]
Oh you can submit i pr

**Comment by drawcall** [comment]
> > -profile:v
> 
> 因为我看到代码里编码格式main好像写死的， .concat([ '-c:v', 'libx264', // c:v - H.264 '-profile:v', 'main', // profile:v - main profile: mainstream image quality. Provide I / P / B frames '-preset', preset, // preset - compromised encoding speed '-movflags', 'faststart', '-pix_fmt', 'yuv420p', '-r', fps, ]);

defaultOutputOptions支持添加自定义ffmpeg命令
'''
new FFCreator({
...,
defaultOutputOptions: {
    merge: false,
    options: ['-pixel_format', 'yuv420p']
},
});
'''
