### ISSUE TITLE
Error: ffmpeg was killed with signal SIGSEGV     at ChildProcess.<anonymous> (/home/createVideo/node_modules/fluent-ffmpeg/lib/processor.js:180:22)

### ISSUE THREAD

**Issue by djwGod** [tnfe/FFCreator#224]
![image](https://user-images.githubusercontent.com/69334634/166885369-a42f249c-1599-4d23-add4-d836bad0b821.png)
有没有人遇到相同的问题求解决

**Comment by nicky132** [comment]
> ![image](https://user-images.githubusercontent.com/69334634/166885369-a42f249c-1599-4d23-add4-d836bad0b821.png) 有没有人遇到相同的问题求解决

我也是这问题,你解决了没

**Comment by djwGod** [comment]
我后来没看了，应该是资源问题，保证你的静态资源都是准备好的，应该就没问题了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月10日 00:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [tnfe/FFCreator] Error: ffmpeg was killed with signal SIGSEGV at ChildProcess.<anonymous> (/home/createVideo/node_modules/fluent-ffmpeg/lib/processor.js:180:22) (Issue #224) |

有没有人遇到相同的问题求解决

我也是这问题,你解决了没
