### ISSUE TITLE
 Error: ffmpeg exited with code 1: /home/createVideo/static/242/cache/rjpmp7bkbftmq61g.txt: Invalid data found when processing input    stdout:    stderr: /home/createVideo/static/242/cache/rjpmp7bkbftmq61g.txt: Invalid data found when processing input

### ISSUE THREAD

**Issue by djwGod** [tnfe/FFCreator#225]
![image](https://user-images.githubusercontent.com/69334634/166887677-44907e5c-bb12-4d79-b4a0-b0c8cf1c463b.png)

**Comment by victorWuxz** [comment]
> ![image](https://user-images.githubusercontent.com/69334634/166887677-44907e5c-bb12-4d79-b4a0-b0c8cf1c463b.png)

请提供复现仓库或者代码，以及运行环境

**Comment by victorWuxz** [comment]
> 辛苦提供复现仓库或者代码，以及运行环境

**Comment by drawcall** [comment]
Please submit ffcreatlite issues here
https://github.com/drawcall/FFCreatorLite/issues
