### ISSUE TITLE
 Error: ffmpeg exited with code 1: /home/createVideo/static/242/cache/r3csst71ixt4pl5y.txt: Invalid data found when processing input

### ISSUE THREAD

**Issue by djwGod** [tnfe/FFCreator#226]
![image](https://user-images.githubusercontent.com/69334634/166899924-959dc266-92fd-4f52-a7b3-aa3a236373f0.png)

![image](https://user-images.githubusercontent.com/69334634/166899838-52f76b74-2e68-4883-b0eb-d8f974ff5c45.png)
唯独没有生成.txt文件不知道啥问题

**Comment by drawcall** [comment]
Please submit ffcreatlite issues here
https://github.com/drawcall/FFCreatorLite/issues
