### ISSUE TITLE
Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by mcl0626** [tnfe/FFCreator#227]
[FF] Creator production error. FFEvent {
type: 'error',
pos: 'preProcessing',
error: "ffmpeg exited with code 1: Output #0, mp3, to '/www/wwwroot/easy/FFCreator-master/examples/cache/2ww76f2sqiwgdq43/video_1_audio.mp3':\n" +
'Output file #0 does not contain any stream\n'
 }

**Comment by Laixinsz** [comment]
这个问题我也遇到了，怎么处理的?我是第一次生成或这样，再次就正常了
Error: ffmpeg exited with code 1: Output #0, mp4, to '/home/songhu/FFCreator/public/results/tkvk6g89fkkpggkq.mp4':
0|ffcreato | Output file #0 does not contain any stream
0|ffcreato | 
0|ffcreato |     at ChildProcess.<anonymous> (/home/songhu/FFCreator/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
0|ffcreato |     at ChildProcess.emit (events.js:400:28)
0|ffcreato |     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
0|ffcreato | [FF] Creator production error. FFEvent {
0|ffcreato |   type: 'error',
0|ffcreato |   pos: 'preProcessing',
0|ffcreato |   error: "Cannot read property 'streams' of null"
0|ffcreato | }
0|ffcreato | Error: ffmpeg was killed with signal SIGKILL
0|ffcreato |     at ChildProcess.<anonymous> (/home/songhu/FFCreator/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
0|ffcreato |     at ChildProcess.emit (events.js:400:28)
0|ffcreato |     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)

**Comment by Christian-Hoeller** [comment]
any updates on this?

**Comment by LLLLevi-y** [comment]
我也遇到这个问题了，没排查出原因

**Comment by lyabs243** [comment]
I have the same issue and I can't still find any solution. Is there an update?
