### ISSUE TITLE
Error initializing complex filters

### ISSUE THREAD

**Issue by 404isNotFound** [tnfe/FFCreator#23]
你好,我使用ffcreatorlite版本在本地合成视频是没有问题的,但是放到liunx上会报错: 
`ffmpeg exited with code 1: Error initializing complex filters`
liunx上ffmpeg 版本为4.3.1  ffcreatorlite 版本为 1.4.7
请问,这是什么问题导致的?

**Comment by xiaocitiao** [comment]
贴出来堆栈信息和参数
这个报错一般是 路径问题

**Comment by 404isNotFound** [comment]
已经解决了,是环境问题,我重新换了台服务器重装了环境就可以正常运行了,但还是非常感谢你!
