### ISSUE TITLE
FFText换行属性wordWrap不生效问题

### ISSUE THREAD

**Issue by 318685465** [tnfe/FFCreator#230]
FFText换行属性wordWrap不生效，还是说text不能是一整行？
![image](https://user-images.githubusercontent.com/20290811/167815502-9e48b14b-ef6f-4d98-be20-b03946b9a0e3.png)

**Comment by drawcall** [comment]
breakWords

**Comment by 318685465** [comment]
> breakWords

thank you @drawcall  that worked

**Comment by nilaybrahmbhatt** [comment]
@drawcall  share the code. where to put breakWords? 

`text2.setStyle({
        breakWords:true,
      });  
`
like this?
