### ISSUE TITLE
每一个scene添加audio的时候能不能自动去除视频的噪音

### ISSUE THREAD

**Issue by qiaoyonjia** [tnfe/FFCreator#235]
每一个scene添加audio的时候能不能去除原视频的背景音
在合成视频的时候，会添加一个合成的音频，现在音频和背景音重复了，能不能去除原上传视频的噪音
scene.addAudio(result);

**Comment by drawcall** [comment]
`
FFVideo(
..audio:false
)
`

**Comment by qiaoyonjia** [comment]
十分感谢，已经解决了
