### ISSUE TITLE
关于动画

### ISSUE THREAD

**Issue by yhd123456** [tnfe/FFCreator#246]
关于文字动画想问一下，我现在有个场景就是 会有个进入动画，然后 进入以后会有个强调动画，然后再有个 退出动画，这三个动画都是加在一个文字元素上面的，text.addEffect(['fadeInUp', 'rotateIn', 'blurIn', 'zoomIn'], 1, 0.5); 这个组合多个动画的方式好像 不可行， 请问有没有什么好的方式可以实现

**Comment by yhd123456** [comment]
> 通过延迟参数控制动画时间

非常感谢，问题已经解决，想再问一下，场景切换特效是不是没办法自定义呀，addAnimate 方法并不能使用

**Comment by drawcall** [comment]
https://tnfe.github.io/FFCreator/#/guide/animate
