### ISSUE TITLE
FFCreatorLite不支持字幕、相册、虚拟主播(可扩展)

### ISSUE THREAD

**Issue by aohuanhuan** [tnfe/FFCreator#248]
如官网文档描述，“FFCreatorLite不支持字幕、相册、虚拟主播(可扩展)” ，FFCreatorLite可以扩展支持字幕吗？如何扩展支持呢？

**Comment by drawcall** [comment]
FFCreator's subtitles is implemented using FFText, so FFCreatorlite can also.
Of course you can also use hard subtitles subtitles=subtitles.srt

**Comment by drawcall** [comment]
Please submit ffcreatlite issues here
https://github.com/drawcall/FFCreatorLite/issues
