### ISSUE TITLE
FFCreatorLite 运行案例 报错

### ISSUE THREAD

**Issue by mcl0626** [tnfe/FFCreator#249]
![image](https://user-images.githubusercontent.com/47437722/179135698-220d2181-0b53-4cd3-bf2d-fcfc3838bc5c.png)
本地环境 linux centos7  
![image](https://user-images.githubusercontent.com/47437722/179135826-25585052-3e1c-4499-911c-2f3dcbf9310b.png)
本地跑着 ffcreator没问题

**Comment by drawcall** [comment]
Please submit ffcreatlite issues here
https://github.com/drawcall/FFCreatorLite/issues
