### ISSUE TITLE
使用素材资源名称包含中文合成视频就会报错[FF] Creator production error，Request path contains unescaped characters.

### ISSUE THREAD

**Issue by Jinkeee** [tnfe/FFCreator#251]
使用素材资源名称包含中文合成视频就会报错[FF] Creator production error，Request path contains unescaped characters.
使用英文名称素材可正常合成。
![微信图片_20220720120259](https://user-images.githubusercontent.com/46039020/179894816-5d7dc799-fac2-4d56-a1df-e9d8ab5589b6.jpg)
使用中文名称素材就会报错[FF] Creator production error，Request path contains unescaped characters.
![微信图片_20220720120245](https://user-images.githubusercontent.com/46039020/179894894-04ab310f-0391-4c09-9271-7111093a4206.jpg)
![image](https://user-images.githubusercontent.com/46039020/179895006-972806f9-7369-43da-981f-2616672ba26b.png)
![微信图片_20220720121113](https://user-images.githubusercontent.com/46039020/179895241-f4fcc449-6897-45bc-951e-9d8e18ddc5c3.png)
还望收到问题原因，帮助解决！感谢！
.

**Comment by drawcall** [comment]
先使用中文path
