### ISSUE TITLE
在 docker 中运行出了问题，求助求助呀

### ISSUE THREAD

**Issue by yhd123456** [tnfe/FFCreator#252]
通过 xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm run dev 可以运行项目没有问题

通过 配置 prcess.josn文件 pm2 start process.json 运行 xvfb 有报错

1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45110) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45124) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45138) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45152) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45166) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45180) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45208) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45222) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45237) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45251) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45265) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45279) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45293) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45307) - No such process
1|xvfb     | /usr/bin/xvfb-run: line 186: kill: (45354) - No such process

1|xvfb  | /usr/bin/xvfb-run: line 181: 99: command not found
1|xvfb  | /usr/bin/xvfb-run: line 186: kill: (45375) - No such process

我的process配置为

{
  "apps" : [{
    "name"        : "koa",
    "script"      : "./src/main.js",
    "env": {
      "DISPLAY": ":99"
    }
  },
    {
      "name"        : "Xvfb",
      "interpreter" : "none",
      "script"      : "Xvfb",
      "args"        : ":99 -ac -screen 0 1280x1024x24"
    }]
}

pm2 为
![企业微信截图_16583015636953](https://user-images.githubusercontent.com/34643400/179921101-53f0f9fd-dbf8-4efa-934e-0e65b0f14619.png)

**Comment by drawcall** [comment]
https://tnfe.github.io/FFCreator/#/qa/qa

**Comment by zdu-strong** [comment]
我的项目里也使用了docker构建ffcreator, 也许你可以参照我的构建脚本. 
项目地址:  https://github.com/zdu-strong/Technical_Backup
Docker构建:   docker build -f docker/default/ffcreator/Dockerfile .
在Docker容器里的/all_code/ffcreator/output下将生成mp4视频.
