### ISSUE TITLE
/lib/utils/date.js cause some error……

### ISSUE THREAD

**Issue by bear-shen** [tnfe/FFCreator#26]
https://github.com/tnfe/FFCreator/blob/3a33bdf242b0d3f944a36fb509c7e5eb54946e65/lib/utils/date.js#L60
https://github.com/tnfe/FFCreator/blob/3a33bdf242b0d3f944a36fb509c7e5eb54946e65/lib/utils/date.js#L71
```
[FF] Synthesis synthesis start: 
ffmpeg -framerate 60 -vcodec rawvideo -pixel_format bgra -video_size 1280x720 
-i /opt/peiyin/resource/cache/j8xn /opt/peiyin/resource/nls/1611649900185.0.mp3 
-i /opt/peiyin/resource/nls/1611649900185.1.mp3 
-i /opt/peiyin/resourc 
-i /opt/peiyin/resource/nls/1611649900185.3.mp3 
-i /opt/peiyin/resource/nls/1611649900185.4.mp3 -y 
-filter_complex 
[1]adelay=0|0[2280[audio1];
[3]adelay=54808|54808[audio2];
[4]adelay=241.944|241.944[audio3];
[5]adelay=254.26399999999998|254.26399999999998[audio4];
[audio0][audio1][audio2][de_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 24 -c:a aac -shortest /resource/nls/1611649900185.mp4
```
date.js 里的这个 toMilliseconds 和 toSeconds 方法中的这个判断。。。 在加入长音频的时候很容易出错的样子，打印出来的合成串里 adelay 明显就是出了错的，手工把这个写死成 `return  time * 1000 ;` 和 `return  time / 1000 ;` 之后工作正常，但是不确定其他地方有没有影响。。。
话说为什么要加这个限制？

**Comment by drawcall** [comment]
Oh, this operation is to provide a friendly api.
Allow users to pass in seconds and milliseconds are compatible. If you think there is a better way, please submit a pr
