### ISSUE TITLE
setFFmpegPath/setFFprobePath在存在subtitle时不生效，会导致App render eror

### ISSUE THREAD

**Issue by linqian02** [tnfe/FFCreator#267]
在没有全局安装ffmpeg的情况下，根据setFFmpegPath/setFFprobePath设置ffmpeg的路径.

感觉是因为在subtitle.js、video.js和gif.js中使用了ffmpeg-probe来读取元数据信息

而该库是使用全局的ffmpeg获取元数据信息的。所以会导致错误；

ffmpeg-probe的代码如下：

```js
'use strict'

const execa = require('execa')

module.exports = async (input, opts = []) => {
  const { stdout } = await execa(process.env.FFPROBE_PATH || 'ffprobe', [
    '-print_format', 'json',
    '-show_error',
    '-show_format',
    '-show_streams',
    ...opts,
    input
  ])

......

```

**Comment by drawcall** [comment]
Oh yes, a simple fix method. 
Set in `setffprobepath` ` process.env. FFPROBE = path` value. Can you help submit a PR.

**Comment by drawcall** [comment]
https://github.com/tnfe/FFCreator/pull/268
