### ISSUE TITLE
Echarts does not work with gl render mode

### ISSUE THREAD

**Issue by kxxoling** [tnfe/FFCreator#272]
The Echarts part is totally missing in my project if I change render mode to `gl` in order to make image blur working. So I made a simple modification on `examples/chart.js`:

```diff
diff --git a/examples/chart.js b/examples/chart.js
index 4656dae..3c068cd 100644
--- a/examples/chart.js
+++ b/examples/chart.js
@@ -38,6 +38,7 @@ const createFFTask = async () => {
     highWaterMark: '3mb',
     parallel: 8,
     audio,
+    render:'gl'
   });
 
   // create FFScene
```

It renders with Echarts animation disabled : https://user-images.githubusercontent.com/1227139/188570770-dff48eb3-82a5-4c7e-a87b-45f5c30dd8fb.mp4 , which is not what I expected.

**Comment by drawcall** [comment]
oh haven't tested echart in gl, maybe you cannot use it
