### ISSUE TITLE
您好，想问下windows环境下执行demo，所有的转场效果都显示黑屏是啥原因

### ISSUE THREAD

**Issue by xukainan** [tnfe/FFCreator#28]

**Comment by drawcall** [comment]
有什么错误提示吗？

**Comment by xukainan** [comment]
看的是没有错误，执行过程如下：
`F:\WebProject\FFCreater>npm run examples

> ffcreator@1.4.1 examples F:\WebProject\FFCreater
> node ./examples/

? Please select the demo you want to run: transition

 --- You can press the s key or the w key to restart! ---

FFCreator start
[FF] renderSceneSingleFrame current scene frames - 300
[FF] renderSceneSingleFrame current scene frames - 300
[FF] renderSceneSingleFrame current scene frames - 300
[FF] renderSceneSingleFrame current scene frames - 300
[FF] renderSceneSingleFrame current scene frames - 300
[FF] Synthesis synthesis start: ffmpeg -framerate 60 -vcodec rawvideo -pixel_format bgra -video_size 600x400 -i F:\WebProject\FFCreater\examples\cache\gmytcqwolyac5ulk\%012d.raw -stream_loop -1 -i F:\WebProject\FFCreater\examples\assets\audio\01.wav -y -filter_complex [1]adelay=0|0[audio0];[audio0]amix=1 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 24 -c:a aac -shortest F:\WebProject\FFCreater\examples\output\0yxp1uaypaxgoqfb.mp4
[FF] Synthesis synthesis progress: 4.44% done
[FF] Synthesis synthesis progress: 6.34% done
[FF] Synthesis synthesis progress: 7.85% done
[FF] Synthesis synthesis progress: 14.28% done
[FF] Synthesis synthesis progress: 21.66% done
[FF] Synthesis synthesis progress: 29.2% done
[FF] Synthesis synthesis progress: 37.14% done
[FF] Synthesis synthesis progress: 40.15% done
------------------------------------------------------
Perf 0 31374 25873960 38961152 66.4% 135184384 66.5%
------------------------------------------------------
FFCreator completed:
 USEAGE: time 31374 memory 25900272 38961152 66.4% 135196672 cpu 66.5%
 PATH: F:\WebProject\FFCreater\examples\output\0yxp1uaypaxgoqfb.mp4

 --- You can press the s key or the w key to restart! ---

[FF] Creator production completed. id:svgddr5fwmxbmlj6 file: F:\WebProject\FFCreater\examples\output\0yxp1uaypaxgoqfb.mp4
[FF] Synthesis synthesis complete`

**Comment by drawcall** [comment]
In x64 system d3dcompiler_47.dll should be in c:\windows\system32, but if isn't then you can find another copy in the deps/ folder.
https://github.com/stackgl/headless-gl/tree/master/deps/windows/dll/x64
