### ISSUE TITLE
添加translation时长校验

### ISSUE THREAD

**Issue by zdu-strong** [tnfe/FFCreator#282]
现在, translation没有translation时长校验, 任意设置translation时长可能会导致以下错误. 
![image](https://user-images.githubusercontent.com/48673442/193405986-05b9ccc3-dcbf-48d4-b7c8-44656e72dc93.png)

代码如下. 由于场景1与场景2的过渡时长为5秒, 场景2与场景3的过渡时长为1秒, 意味着场景2最长需要有6秒的时长. 现在场景2的时长是5秒, 是不够的.
![image](https://user-images.githubusercontent.com/48673442/193405826-3662851a-69be-4a29-9a8b-dd7c9750ec17.png)

**Comment by zdu-strong** [comment]
很好, 我将添加一个检查, 在FFCreator.start()方法里进行调用.

**Comment by zdu-strong** [comment]
> 哦 欢迎提交pr

Please check the pull request

**Comment by zdu-strong** [comment]
> 帮你催了一下看看PR，再等等哈

Thank you so much

**Comment by drawcall** [comment]
Wait a minute. Check any things later.

**Comment by zdu-strong** [comment]
Although I know FFCreator.addChild(FFScene), so check transition duration of all FFScene.
But I'm ignoring whether FFCreator can add other types of children, and whether they affect the transition duration.

Please let me know if this is clear to you.
