### ISSUE TITLE
是否有API能够查询已初始化的模板

### ISSUE THREAD

**Issue by zangguojun** [tnfe/FFCreator#284]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/49148972/193726462-439c4f16-8f5f-42e6-b7e4-ea40d3f2fe3c.png">
如果我拥有多个模板，上面图片中的意思应该是每个模板都需要提前做类似“初始化”的Action，那么我如何查询到，哪些模板我已经做了初始化，因为我需要做下述伪代码：

```js
function(tempId, tempInfo) {
  if(未初始化当前模板) {
    调用初始化模板方法
  }
  FFCreatorCenter.addTaskByTemplate(tempId, tempInfo);
}
```

**Comment by drawcall** [comment]
get !!FFCreatorCenter.temps[id]

**Comment by zangguojun** [comment]
😯so easy
