### ISSUE TITLE
如何实现类似 文字跳动的效果 呢

### ISSUE THREAD

**Issue by CavinHuang** [tnfe/FFCreator#291]
经过尝试，目前还是无法正确的实现类似 滚动歌词 这样的文字动画 ，包含 如剪映 音符跳动文字 的效果以及歌词往上滚动的效果。

**Comment by drawcall** [comment]
There is a simple animation option in subtitles. Complex animation can be write by yourself

**Comment by hjkltop** [comment]
> I will write a demo with like effects later
您好，能否分享下effect文件，我们想做个文字按字弹出的效果。

**Comment by yeeddd** [comment]
> I will write a demo with like effects later

你好，这个demo有了吗？
