### ISSUE TITLE
多个视频不能同时生成

### ISSUE THREAD

**Issue by chin-ray** [tnfe/FFCreator#295]
生成视频时需要等待上一个视频生成完成之后才能开始  也就是state=busy  请问这是有某种原因还是为了其他错误而安置的判断条件呢

**Comment by chin-ray** [comment]
When generating a video, you need to wait until the last video is generated, that is, state=busy

**Comment by drawcall** [comment]
在FFCreatorCenter中控制，FFCreatorCenter只是官方的一个实现。你可以实现一个自己的manager

**Comment by chin-ray** [comment]
FFCreatorCenter中使用了任务队列的形式实现多任务生成输出，有没有办法让串行多任务生成变成并行的呢  意思就是说当我多个人进行视频合成，第二个人必须等待第一个人视频合成完成之后才能开始start方法进行合成  有没有办法使得两个人无需等待其他人呢

**Comment by chin-ray** [comment]
OK 已经解决了 最后还是把 FFCreatorCenter 的部分方法重写了

**Comment by mannymu** [comment]
我重新了  FFCreatorCenter , 在自己的 mac 上跑 5 个视频同时渲染，出来的视频会非常卡顿。
