### ISSUE TITLE
并发合成时视频被加速

### ISSUE THREAD

**Issue by chin-ray** [tnfe/FFCreator#297]
并发生成视频的时候，生成出的视频前半部分被加速，后半部分出现卡帧现象

**Comment by drawcall** [comment]
https://tnfe.github.io/FFCreator/#/qa/qa?id=%e2%9c%bf5-centos%e4%b8%8b%e5%90%88%e6%88%90%e8%a7%86%e9%a2%91%e6%97%b6%e9%98%bb%e5%a1%9ehttp%e8%af%b7%e6%b1%82

**Comment by drawcall** [comment]
use cluster or?

**Comment by chin-ray** [comment]
感谢作者的解答  目前没有使用cluster  原因是node开发经验不够  所以之前的并行方案取消了  改成串行的了
