### ISSUE TITLE
FFcreator似乎不支持在线的资源，如在线图片等

### ISSUE THREAD

**Issue by linqian02** [tnfe/FFCreator#312]
能使其支持在线资源吗

**Comment by drawcall** [comment]
支持的
https://github.com/tnfe/FFCreator/blob/master/examples/preload.js

**Comment by linqian02** [comment]
> 支持的 https://github.com/tnfe/FFCreator/blob/master/examples/preload.js

我的某些图片不行，打断点看了下，发现在canvas加载图片时报错：certificate has expired。
似乎是和证书相关，我在修改canvas的代码，在请求中加入： rejectUnauthorized:false 来解决上述问题。
thanks !
