### ISSUE TITLE
字幕的背景色可以不要的吗？去掉backgroundColor 默认还是蓝色

### ISSUE THREAD

**Issue by f1748x** [tnfe/FFCreator#320]
const subtitle = new FFSubtitle({
    comma: true, // 是否逗号分割
    //backgroundColor: '#00219C',//注释这行还是背景色蓝色
    color: '#fff',
    fontSize: 32,
    x: width / 2,
    y: height / 2 + 300,
  });

**Comment by drawcall** [comment]
https://github.com/tnfe/FFCreator/issues/193
