### ISSUE TITLE
在electron上运行require ffcreator报错

### ISSUE THREAD

**Issue by wth1107** [tnfe/FFCreator#348]
electron 24.1.2 node 18.14.0  ffcreator ^7.0.3    运行在win10系统
App threw an error during load
Error: The module '\\?\D:\project\electron\ef3\node_modules\.store\gl@6.0.2\node_modules\gl\build\Release\webgl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 114. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (D:\project\electron\ef3\node_modules\.store\bindings@1.5.0\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (D:\project\electron\ef3\node_modules\.store\gl@6.0.2\node_modules\gl\src\javascript\native-gl.js:1:40)

尝试了官方的.\node_modules\.bin\electron-rebuild.cmd 但仍未解决问题 ，哪位大佬给点建议！！

**Comment by drawcall** [comment]
Will provide a full electron demo if I have time

**Comment by wth1107** [comment]
@drawcall 期待

**Comment by linqian02** [comment]
> Will provide a full electron demo if I have time

@drawcall  我尝试在electron中使用，但由于node-canvas和gl的限制，这似乎不太可能。大概原因是因为两者都用到了nan这个 C++ 库...

[@https://github.com/Automattic/node-canvas/issues/2200](https://github.com/Automattic/node-canvas/issues/2200)

我也很期待在electron中运行的demo

**Comment by vutienhc** [comment]
I got the same error. Please help me. Thank you.

**Comment by vutienhc** [comment]
@wth1107 Have you found a solution yet?

**Comment by wth1107** [comment]
> 

没有啊，我在等待作者的demo

**Comment by wth1107** [comment]
@vutienhc @linqian02 好大哥们  有招了吗

**Comment by wangmode** [comment]
@drawcall electron demo 这个有空搞下吧🙇‍

**Comment by zjqiudan** [comment]
求demo，等了快1年了....

**Comment by wth1107** [comment]
半年了。。。o(╥﹏╥)o

**Comment by ahnuchen** [comment]
@drawcall 大哥，有招了吗

**Comment by drawcall** [comment]
先使用这个项目 https://github.com/tnfe/FFCreator/issues/435 ，ffcreator结合electron我后面会更新

**Comment by 2284730142** [comment]
基本上是因为inkpaint的底层用了headless-gl和node-canvas，这两块如果能用electron自带内容编译的话，就没有问题了，但是问题关键就是这两个东西，node-canvas强制切换到3.0-alpha能够正常编译通过，且能够使用，但是headless，使用较新的electron-rebuild，无法编译通过，因为它只支持nan

**Comment by xeoshow** [comment]
@2284730142 headless-gl和node-canvas确实安装搭建非常麻烦。有个借助于rust的零依赖的canvas，看着API完全一样，也几乎都实现了，性能还要好得多。要是FFCreator项目里的canvas可以用这个平替，估计好很多。那个canvas的开发作者技术也非常非常牛，做了很多影响力和star很多的开源项目，都非常受欢迎。
```
https://github.com/Brooooooklyn/canvas
```

**Comment by msudomoikin** [comment]
Hey everyone. 

I also was struggling with native modules (node-canvas, headless-gl), couldn't rebuild them for electron runtime. So I've ended with this solution.

I've copied my app code, node_modules and node.exe (version that I used to develop, native modules were built against it) to an electron resources folder, and then in electron I run my app with that standalone node binary. 

Project structure is
```
/backend
  node_modules
  src/app.js
/electron
  main.js
/node
  node.exe
```
backend folder is where my node app with ffcreator
electron is electron project :)
node is folder with unpacked windows binaries. same version with which I developed and installed packages in backend folder.


Here's package.json for electron, notice --extraResource parameters in package script to copy my app and node binary
```json
{
  "name": "myElectronApp",
  "version": "1.0.0",
  "main": "main.js",
  "type": "module",
  "scripts": {
    "start": "electron .",
    "package": "electron-packager . --overwrite --platform=win32 --arch=x64 --prune=true --out=dist  --extraResource='../backend' --extraResource='../nodejs/node.exe'" 
  },
  "author": "Matvey Sudomoykin me@matveymatvey.com",
  "devDependencies": {
    "electron": "^33.1.0",
    "electron-packager": "^17.1.2"
  }
}
```

Then I can run my app from electron like so
```javascript
// /electron/main.js

const node = path.join(process.resourcesPath, "node.exe"); //path to copied node binary
const nodeModulesBackend = path.join(process.resourcesPath, "backend", "node_modules"); //path to copied node_modules
const app = [path.join(process.resourcesPath, "backend", "src", "app.js")] //path to my app entry file

//command to run my app with copied node binary
backendProcess = spawn(
    node,
    app,
    {
      env: { ...process.env, NODE_PATH: nodeModulesBackend },
      cwd: path.join(process.resourcesPath, "backend"),
    }
  );
```

I can communicate between electron and my app with `ipcMain` (show if app has started, display console output and such).
To package everything I'm using electron-packager, same can be done with electron-builder if you need msi.

I'ts not very elegant solution, but it works. I can ship my code to a customer as a desktop app, without needing them to install node. Also they get nice GUI to run and control app, without terminal screens, bat-files or other ugly things.

Hope this helps someone!
