### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by NikyPeng** [tnfe/FFCreator#35]
定时执行视频生成，主进程内存不断升高

**Comment by drawcall** [comment]
Can you send me the demo code and memory growth

**Comment by NikyPeng** [comment]
> Can you send me the demo code and memory growth



> Can you send me the demo code and memory growth

ok,your email ?

**Comment by NikyPeng** [comment]
> Can you send me the demo code and memory growth

This problem is caused by module named Pool. Especially FFText

**Comment by drawcall** [comment]
Oh, please download the latest version, the Pool object pool is not enabled by default. And the problem of FFText has been fixed, thanks

**Comment by NikyPeng** [comment]
> Oh, please download the latest version, the Pool object pool is not enabled by default. And the problem of FFText has been fixed, thanks

ask a question, when snapshot is only 180kb,Under H264 and yuv420p conditions, run ffmpeg  command, it has an error with packet size 180000 < expected frame_size 3686400. How to fix?
