### ISSUE TITLE
使用Vtuber的setCutoutColor去除视频的绿幕，处理完的视频里的人物仍然有绿色边框，没处理完全，如何解决

### ISSUE THREAD

**Issue by wth1107** [tnfe/FFCreator#357]
const fvtuber = new FFVtuber({ path: vtuber, x: 0, y: height, width: 480, height: 480 });
fvtuber.setCutoutColor(110, 130);
scene1.addChild(fvtuber);

**Comment by drawcall** [comment]
修改 min, max, colormin, colormax

**Comment by wth1107** [comment]
修改过 colormin, colormax了，但是处理后的视频任务边界处 仍比较明显 
![image](https://github.com/tnfe/FFCreator/assets/124866107/99e224e4-2204-4ea6-9d27-20c233fdd0df)
而且锯齿感很强，手动用ffmpeg处理过的视频就 好很多 
![image](https://github.com/tnfe/FFCreator/assets/124866107/a153b848-12aa-437c-a9de-090de72e07f2)
人物轮廓较圆滑，我该如何解决呢

**Comment by Woods30** [comment]
请问下这个问题最后是怎么处理的呢？@wth1107
