### ISSUE TITLE
添加的视频元素不存在音频流时合成出错

### ISSUE THREAD

**Issue by linqian02** [tnfe/FFCreator#361]
如下
![image](https://github.com/tnfe/FFCreator/assets/29908531/4d9962e3-84a7-4899-b96e-c7caf086663d)

类似的问题：
[245](https://github.com/tnfe/FFCreator/issues/245)

**Comment by linqian02** [comment]
提了个Pr ，有时间麻烦检查一下呀 @drawcall 

#362

**Comment by linqian02** [comment]
> 提了个Pr ，有时间麻烦检查一下呀 @drawcall
> 
> #362

eslint存在问题，网络突然拉不下来代码了，后面我再重新提个Pr...

**Comment by linqian02** [comment]
> > 提了个Pr ，有时间麻烦检查一下呀 @drawcall
> > #362
> 
> eslint存在问题，网络突然拉不下来代码了，后面我再重新提个Pr...

#363

**Comment by drawcall** [comment]
ok
