### ISSUE TITLE
Creator production error. "Cannot read property 'destroy' of undefined"

### ISSUE THREAD

**Issue by Sunshine-node** [tnfe/FFCreator#374]
想问一下 执行destroy方法提示undefined 我看FFCreator类里面有这个方法

**Comment by drawcall** [comment]
如何执行的？

**Comment by Sunshine-node** [comment]
> 如何执行的？

    const creator = new FFCreator({
        cacheDir,
        outputDir,
        output,
        width,
        height,
        debug: false,
        highWaterMark: '3mb'
    });

creator.start();
........
..........
// 会出现Cannot read property 'destroy' of undefined
 creator.destroy();
在ts的话 还提示用destory()

**Comment by JunVincetHuo** [comment]
同样遇到该问题，打印出来destroy是undefined

**Comment by drawcall** [comment]
```
this.renderer.on('error', destroy);
this.renderer.on('complete', destroy);
```
渲染结束回自动destroy无需手动操作

**Comment by 13rj113** [comment]
以下是我的代码creator.on('complete', destroy);
好像不行，会报错找不到名称“destroy”

**Comment by 13rj113** [comment]
> ```
> this.renderer.on('error', destroy);
> this.renderer.on('complete', destroy);
> ```
> 
> 渲染结束会自动destroy无需手动操作

能再详细一些吗
