### ISSUE TITLE
请问如何运行?

### ISSUE THREAD

**Issue by code789** [tnfe/FFCreator#38]
小白求教:
missing script: start

如何创建项目

如何启动项目

文档里写的不是很清晰

如何把案例运行起来?

**Comment by drawcall** [comment]
npm run examples .Or you can refer to this example
https://github.com/video-factory/video-demo

**Comment by code789** [comment]
> npm run examples or you can refer to this example
> https://github.com/video-factory/video-demo

谢谢  运行起来了  
先clone,然后npm install 然后npm run ./examples
