### ISSUE TITLE
这个案例代码有吗？在哪里啊

### ISSUE THREAD

**Issue by f1748x** [tnfe/FFCreator#382]
<img width="794" alt="image" src="https://github.com/tnfe/FFCreator/assets/21169782/b220f570-0de6-4f11-8a1a-3cd8234c1fb9">

**Comment by drawcall** [comment]
sorry最近有点忙，这个case有点复杂，整理需要点时间。

**Comment by f1748x** [comment]
> 



> 抱歉最近忙有点，这个案子有点复杂，整理需要点时间。

请问有时间了吗？
