### ISSUE TITLE
FFcreator可以实现肯·伯恩斯(Ken burns)效果吗

### ISSUE THREAD

**Issue by lqomg** [tnfe/FFCreator#396]
这是指让图片缓慢缩放或平移，以达到转移兴趣点的一种效果。这对于记录片之类的很有用。
就像这样：[https://www.kirupa.com/html5/ken_burns_effect_css.htm](https://www.kirupa.com/html5/ken_burns_effect_css.htm);
或者说如何自定义动画能不能给某一时刻的关键帧，感觉这样就可以实现了

**Comment by Vinlic** [comment]
也许我最新开源的这个项目能够帮助你：[https://github.com/Vinlic/WebVideoCreator](https://github.com/Vinlic/WebVideoCreator)
这个视频是使用WebVideoCreator渲染获得的

https://github.com/tnfe/FFCreator/assets/20235341/18ee6693-519c-4f05-a71d-4eabd6722534

**Comment by lqomg** [comment]
> 也许我最新开源的这个项目能够帮助你：https://github.com/Vinlic/WebVideoCreator 这个视频是使用WebVideoCreator渲染获得的
> 
>  t.mp4

谢谢 我试试
