### ISSUE TITLE
有实时预览的编辑器吗

### ISSUE THREAD

**Issue by nws123045088** [tnfe/FFCreator#398]
类似微信开发工具那样改代码可以看到实时的视频效果

**Comment by nws123045088** [comment]
不一定要求实时 几秒延迟也ok

**Comment by zdu-strong** [comment]
Using FFCreator and vue.js, you can develop a web project that builds video by dragging and dropping, just as the h5 building tool. You can check it [here](https://github.com/tnfe/shida).

**Comment by yangshen2000** [comment]
没有

**Comment by drawcall** [comment]
https://github.com/tnfe/shida
