### ISSUE TITLE
Creating outputDir with the FFCreator instance

### ISSUE THREAD

**Issue by khatiwadaaj** [tnfe/FFCreator#405]
const cacheDir = join(__dirname, "../cache/");
 const outputDir = join(__dirname, "../video/");

// create creator instance
  const width = 1080;
  const height = 1920;
  const creator = new FFCreator({
    cacheDir: cacheDir,
    outputDir: outputDir,
    width: width,
    height: height,
    //   log: true,
    highWaterMark: "8mb",
    parallel: 1,
    fps: 30,
  });

I have something like this, but it always creates the videos in / directory of where my index.js of project is.
Am I missing something?
Please direct me towards anything that is helpful.

**Comment by zdu-strong** [comment]
Please use output.

    const output = join(__dirname, "../video/video.mp4");

    // create creator instance
    const width = 1080;
    const height = 1920;
    const creator = new FFCreator({
      cacheDir: cacheDir,
      output: output,
      width: width,
      height: height,
      // log: true,
      highWaterMark: "8mb",
      parallel: 1,
      fps: 30,
    });

**Comment by yeeddd** [comment]
mark

**Comment by yeeddd** [comment]
> output: output,
>   width: width,

请问下 output 和outputDir ，分别是啥作用，以及有啥区别？我看example中使用outputDir就能正常输出在对应目录，而我就是在当前目录生成。不知道啥原因。
