### ISSUE TITLE
字体乱码是怎么回事？

### ISSUE THREAD

**Issue by liuxiaojinla** [tnfe/FFCreator#419]
![WX20240219-180422](https://github.com/tnfe/FFCreator/assets/16009864/f34645de-1cba-4616-a1a8-a8dfcaeac0b0)

**Comment by drawcall** [comment]
Use TrueType font

**Comment by liuxiaojinla** [comment]
这个问题之前没有出现过，最近更新了依赖包，就出现这个问题了

**Comment by liuxiaojinla** [comment]
> Use TrueType font
这个问题之前没有出现过，最近更新了依赖包，就出现这个问题了

**Comment by liuxiaojinla** [comment]
> Title

程序刚启动的期间没有任何问题，当程序跑了一段时间后，就很频繁的出现字体乱码的现象，不是每次都会出现乱码，但是随着程序的运行的时间越来越长，这个乱码的现象就越频繁，现在是人工手动重启程序才能解决这个问题

**Comment by drawcall** [comment]
使用 TrueType font
