### ISSUE TITLE
Can a function be added? Let me set the start time and duration of the element in the scene.

### ISSUE THREAD

**Issue by zduIsMe** [tnfe/FFCreator#42]

**Comment by drawcall** [comment]
Oh, what effect do you want to achieve, scene elements can appear and disappear through animation control

**Comment by zhiling1A** [comment]
I have some videos that I want to add to the scene, but they will start playing after a certain delay.

**Comment by drawcall** [comment]
@zduIsMe 
```
element.addEffect("fadeIn" , 1, 1);
element.addEffect("fadeOut" , 1, 3);
```

@zdu-strong Regarding the flexible operation of the video, you can use ffcreatorlite.
