### ISSUE TITLE
Centos7.3.1611 上不支持显示 jpg 格式的图片

### ISSUE THREAD

**Issue by huipengo** [tnfe/FFCreator#450]
Centos7.3.1611
Node: 16.13.1
Canvas: 2.11.2
ffmpeg: 6.1

我拉取的最新代码跑的：xvfb-run -s "-ac -screen 0 1280x1024x24" npm run examples
第一个示例

jpg格式的图片显示不出来，png 的没问题
Mac 上 jpg 格式的图片可以显示出来

大佬，请问啥问题呢？

**Comment by drawcall** [comment]
sudo yum install gcc-c++ cairo-devel pango-devel libjpeg-turbo-devel giflib-devel .Note the version

**Comment by huipengo** [comment]
> sudo yum install gcc-c++ cairo-devel pango-devel libjpeg-turbo-devel giflib-devel .Note the version
嗯，感谢大佬解答，这些依赖库都有安装的。
我使用的canvas 2.11.2 还是有这个问题，其他依赖库的版本
Package gcc-c++-4.8.5-11.el7.x86_64 already installed and latest version
Package cairo-devel-1.14.2-1.el7.x86_64 already installed and latest version
Package pango-devel-1.36.8-2.el7.x86_64 already installed and latest version
Package libjpeg-turbo-devel-1.2.90-5.el7.x86_64 already installed and latest version
Package giflib-devel-4.1.6-9.el7.x86_64 already installed and latest version

**Comment by shelleyCoco** [comment]
> > sudo yum install gcc-c++ cairo-devel pango-devel libjpeg-turbo-devel giflib-devel .Note the version
> > 嗯，感谢大佬解答，这些依赖库都有安装的。
> > 我使用的canvas 2.11.2 还是有这个问题，其他依赖库的版本
> > Package gcc-c++-4.8.5-11.el7.x86_64 already installed and latest version
> > Package cairo-devel-1.14.2-1.el7.x86_64 already installed and latest version
> > Package pango-devel-1.36.8-2.el7.x86_64 already installed and latest version
> > Package libjpeg-turbo-devel-1.2.90-5.el7.x86_64 already installed and latest version
> > Package giflib-devel-4.1.6-9.el7.x86_64 already installed and latest version

想问下最后怎么解决的
