### ISSUE TITLE
动画效果切换时有卡顿

### ISSUE THREAD

**Issue by xiaojiu007** [tnfe/FFCreator#46]
//场景五
  const fbg5 = new FFImage({path: bg, x: width / 2, y: height / 2});
  scene5.addChild(fbg5);
  const wubigti = new FFText({text: '污水处理设备'});
  wubigti.setXY(86, 185);  
  wubigti.setColor('#f90909');   // 背景色
  wubigti.addEffect('fadeInDown', 1, 0.8); 
  wubigti.setStyle({fontSize:112,fontWeight:700,fontFamily:'SimHei'});   // 设置样式object 
  scene5.addChild(wubigti);
  const kwu1 = new FFImage({path: kuang});
  kwu1.setXY(864, 1204);   
  kwu1.setAnchor(1);
  kwu1.setWH(640, 480); 
  kwu1.addEffect('backInRight', 1, 0.8);
  scene5.addChild(kwu1);
  const tuwu1 = new FFImage({path: wuimg});
  tuwu1.setXY(844, 1184);   
  tuwu1.setAnchor(1);
  tuwu1.setWH(600, 440); 
  tuwu1.addEffect('backInRight', 1, 0.8);
  scene5.addChild(tuwu1);
  const wuti1 = new FFText({text: '造纸污水处理'});
  wuti1.setXY(width / 2, 1248);  
  wuti1.setColor('#f60c0c');   // 背景色
  wuti1.addEffect('fadeInDown', 1, 0.8);         // 动画
  wuti1.alignCenter();                         // 文字居中
  wuti1.setStyle({fontSize:48,fontWeight:900,fontFamily:'SimHei'});   // 设置样式object 
  scene5.addChild(wuti1);
  scene5.setDuration(4);
  scene5.setTransition('Lens', 1.5);
  creator.addChild(scene5);
  
    //场景六
  const fbg6 = new FFImage({path: bg, x: width / 2, y: height / 2});
  scene6.addChild(fbg6);
  const liuti = new FFText({text: '专业污水处理厂家'});
  liuti.setXY(width/2, height/2);  
  liuti.setColor('#f90e0e');   // 背景色
  liuti.addEffect('fadeInDown', 1, 0.8);         // 动画
  liuti.alignCenter();                         // 文字居中
  liuti.setStyle({fontSize:100,fontWeight:700,fontFamily:'SimHei'});   // 设置样式object 
  scene6.addChild(liuti);
  scene6.setDuration(4);
  scene6.setTransition('Radiation', 1.5);
  creator.addChild(scene6);
  
  场景五切换到场景六时 场景6会有场景5的一些图片 等会就没了 为什么呢

**Comment by drawcall** [comment]
I tested your code and found no problems
