### ISSUE TITLE
在linux系统，提示webGl不可用

### ISSUE THREAD

**Issue by wwqking** [tnfe/FFCreator#49]
在linux系统，提示webGl不可用

**Comment by drawcall** [comment]
Please check QA in the readme

**Comment by wwqking** [comment]
![image](https://user-images.githubusercontent.com/20062330/123892701-abbf7700-d98d-11eb-8119-f3c4cbd6d03f.png)
结果又出现了另外一个问题

**Comment by drawcall** [comment]
Oh, I think it’s your ffmpeg compiled version problem, you can install the official guidelines to compile a basic version

**Comment by wwqking** [comment]
![image](https://user-images.githubusercontent.com/20062330/123907746-f995a880-d9a8-11eb-97f8-cc0b8c4fe445.png)
这已经是最新版本的了，还是不行

**Comment by drawcall** [comment]
Set compile libx264 parameters
[https://stackoverflow.com/questions/20035338/ffmpeg-on-heroku-unrecognized-option-preset](https://stackoverflow.com/questions/20035338/ffmpeg-on-heroku-unrecognized-option-preset)
