### ISSUE TITLE
你好，想请教一下FFVideo 方法对传入视频的要求是什么

### ISSUE THREAD

**Issue by rulaishenzhang** [tnfe/FFCreator#55]
我从网上下载了一个mp4视频，之后

`
const bgVideo = path.join(__dirname, './assets/video2.mp4');

const bg = new FFVideo({
    path: bgVideo,
    width: width,
    height: height
})
scene1.addChild(bg)

`

发现生成失败了

**Comment by drawcall** [comment]
What reported an error. If you want to process videos in Dali, also use ffcreatorlite

**Comment by rulaishenzhang** [comment]
是我的电脑问题，代码挪到同事电脑上是可以的
