### ISSUE TITLE
FFVideo Audio preProcessing errorAudio codec libmp3lame is not available

### ISSUE THREAD

**Issue by fyrichy** [tnfe/FFCreator#57]
[
![报错](https://user-images.githubusercontent.com/28641320/124731439-d046c080-df44-11eb-9922-baa85fc0770a.png)
](url)

**Comment by fyrichy** [comment]
FFCreator start
[FF] FFVideo Audio preProcessing errorAudio codec libmp3lame is not available
FFCreator error: Audio codec libmp3lame is not available
[FF] Creator production error. [object Object]
(node:93173) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'destroy' of undefined
    at Renderer.destroy (/opt/FFCreator/lib/core/renderer.js:439:20)
    at FFCreator.destroy (/opt/FFCreator/lib/creator.js:323:19)
    at Renderer.errorHandler (/opt/FFCreator/lib/creator.js:303:12)
    at Renderer.emit (events.js:315:20)
    at EventHelper.emitError (/opt/FFCreator/lib/event/helper.js:65:17)
    at Renderer.preparedMaterials (/opt/FFCreator/lib/core/renderer.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Renderer.start (/opt/FFCreator/lib/core/renderer.js:61:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:93173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:93173) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[FF] FFVideo Video preProcessing errorffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error
frame=    3 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=0.259x    
video:765kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

**Comment by drawcall** [comment]
Oh, I think it’s your ffmpeg compiled version problem
