### ISSUE TITLE
ERROR: ffmpeg exited with code 1: Unrecognized option 'preset'.

### ISSUE THREAD

**Issue by fyrichy** [tnfe/FFCreator#58]
FFCreator error: {"type":"normal","output":"","error":"ffmpeg exited with code 1: Unrecognized option 'preset'.\nError splitting the argument list: Option not found\n","state":"","command":null,"percent":0,"pos":"Synthesis"}
[FF] Creator production error. [object Object]
[FF] Synthesis stdout: 
 stderr:Unrecognized option 'preset'.
Error splitting the argument list: Option not found
ffmpeg exited with code 1: Unrecognized option 'preset'.
Error splitting the argument list: Option not found

**Comment by drawcall** [comment]
https://github.com/tnfe/FFCreator/issues/49
