### ISSUE TITLE
Error: FFCreator error: ffmpeg exited with code 1: Unrecognized option 'preset'.

### ISSUE THREAD

**Issue by fyrichy** [tnfe/FFCreator#59]
FFCreator error: ffmpeg exited with code 1: Unrecognized option 'preset'.
Error splitting the argument list: Option not found

[FF] Creator production error. [object Object]
[FF] Synthesis stdout: 
 stderr:Unrecognized option 'preset'.
Error splitting the argument list: Option not found
ffmpeg exited with code 1: Unrecognized option 'preset'.
Error splitting the argument list: Option not found

**Comment by drawcall** [comment]
https://github.com/tnfe/FFCreator/issues/49
