### ISSUE TITLE
Error: FFLogger.enable is not a function

### ISSUE THREAD

**Issue by kishorek** [tnfe/FFCreator#6]
Whenever I try to process huge videos, I am encountering the below error. Can anyone help?

`Error FFLogger.enable is not a function`

**Comment by drawcall** [comment]
Oh, thank you for your feedback, it has been fixed, please upgrade to v1.3.3

**Comment by drawcall** [comment]
Oh, if there is a video in your material, I recommend you to use [FFCreatorLite](https://github.com/tnfe/FFCreatorLite), FFCreatorLite can process the video very fast

https://github.com/tnfe/FFCreatorLite

**Comment by kishorek** [comment]
Thank you @drawcall I can confirm this is working now. I will use FFCreatorLite as you suggested.
