### ISSUE TITLE
how to set audio endTime

### ISSUE THREAD

**Issue by justyeh** [tnfe/FFCreator#62]
I have a loog time audio, but I only want to play the beginning part, how do I set the end time of the audio, just like the setTimes method of video

**Comment by zwgdrs** [comment]
暂时应该还没有实现这个功能。不过感觉这个功能确实比较重要，我这边在进行视频合成的时候也需要用到

**Comment by drawcall** [comment]
Oh I'm working on the next version. Mark this point

**Comment by drawcall** [comment]
Please download the new version

https://github.com/tnfe/FFCreator/blob/master/examples/text.js
