### ISSUE TITLE
Convert time to millisecond format issue 

### ISSUE THREAD

**Issue by baiy** [tnfe/FFCreator#64]
https://github.com/tnfe/FFCreator/blob/8f9ab99a9448af665d8d8bd4b78a0bc8382ae9c0/lib/utils/date.js#L52-L73

这在转换时间到毫秒是 时间大于100秒是就不在进行转换 是基于什么原因 

现在当添加的tts累积超过100秒后  会出现声音叠加的情况 我排查原因就是这里转换时间是造成音频延迟计算错误

**Comment by longxianglu** [comment]
同问

**Comment by drawcall** [comment]
Oh that was a fault-tolerant solution, OK now I give up.
