### ISSUE TITLE
能否使用 NVIDIA GPU进行视频编解码，以提升速度

### ISSUE THREAD

**Issue by 121786404** [tnfe/FFCreator#65]
RT

**Comment by drawcall** [comment]
Oh, I'm upgrading the rendering engine, of course you can customize your own ffmpeg for hardware acceleration

**Comment by 121786404** [comment]
请问有计划做这个feature吗，我刚接触这个项目。如果能实现GPU解码 GPU特效 GPU编码 完全不需要主机的内存和CPU，那就完美了。感谢腾讯开源的这个项目！

**Comment by szmario** [comment]
同问，在linux下使用xvfb能顺利启动，但无法启用gpu加速，处理速度比win模式慢？

**Comment by longxianglu** [comment]
我跑了代码，看日志发现还是canvas动画转图片帧慢，这块要是能支持多线程和gpu加速就完美了！现在提高硬件资源，对视频渲染的速度帮助也不大。

**Comment by 121786404** [comment]
> 同问，在linux下使用xvfb能顺利启动，但无法启用gpu加速，处理速度比win模式慢？

遇到同样的问题，如何指定用Nvidia的GPU，而不是集成显卡?

**Comment by drawcall** [comment]
Oh, the performance bottleneck is not rendering, storing binary data in the cairo library (maybe I will find a way to optimize it when I have time).

This example can improve performance. 
[https://github.com/tnfe/FFCreator/blob/master/examples/fps.js](https://github.com/tnfe/FFCreator/blob/master/examples/fps.js)

**Comment by drawcall** [comment]
If you like faster speed, you can use ffcreatorlite. It can do a lot of things. I like this library very much.
