### ISSUE TITLE
背景音乐能否在最后两秒渐弱？

### ISSUE THREAD

**Issue by zhouxin120** [tnfe/FFCreator#66]
如题

**Comment by zhouxin120** [comment]
参见这个：https://video.stackexchange.com/questions/19867/how-to-fade-in-out-a-video-audio-clip-with-unknown-duration

**Comment by drawcall** [comment]
@baiy baiy Maybe you can write thanks

**Comment by drawcall** [comment]
The function has been implemented, please use the new version.
