### ISSUE TITLE
生成的视频能否生成一个缩略图做封面？

### ISSUE THREAD

**Issue by zhouxin120** [tnfe/FFCreator#67]
如题

**Comment by zhouxin120** [comment]
参见这个：https://stackoverflow.com/questions/54717175/how-do-i-add-a-custom-thumbnail-to-a-mp4-file-using-ffmpeg

**Comment by drawcall** [comment]
@baiy  baiy Maybe you can write thanks

**Comment by drawcall** [comment]
Oh i'm working on the next version, wait a while

**Comment by drawcall** [comment]
The function has been implemented, please use the new version
