### ISSUE TITLE
实现视频高斯模糊拓边效果

### ISSUE THREAD

**Issue by 121786404** [tnfe/FFCreator#68]
https://blog.csdn.net/ternence_hsu/article/details/104020716
纯色的背景太单调了，这种毛玻璃的背景会好很多。

**Comment by drawcall** [comment]
Oh, I think [ffcreatorlite](https://github.com/tnfe/FFCreatorLite) can achieve this function

**Comment by DZwangbing** [comment]
> https://blog.csdn.net/ternence_hsu/article/details/104020716 纯色的背景太单调了，这种毛玻璃的背景会好很多。

请问通过ffCreator实现高斯模糊滤镜了么？
