### ISSUE TITLE
Error initializing complex filters，是不是FFcreatorlite库调用ffmpeg传参的问题呢？

### ISSUE THREAD

**Issue by HuaiJiangTao** [tnfe/FFCreator#70]
`Error: ffmpeg exited with code 1: Error initializing complex filters.
Invalid argument
 
 stdout:  
 stderr: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/apple/Desktop/sogou/ffcreator/cache/dofmsb8dwqufceum/scene1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:08.50, start: 0.000000, bitrate: 172 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1280 [SAR 1:1 DAR 3:2], 99 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 404x604 [SAR 1:1 DAR 101:151], 192 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
[AVFilterGraph @ 0x7f9f497092c0] No such filter: ''
Error initializing complex filters.
Invalid argument`

**Comment by HuaiJiangTao** [comment]
scene.setTransition

**Comment by lidan-web** [comment]
出现这个问题是ffmpeg版本问题，转场动画要求ffmpeg4.3以上
