### ISSUE TITLE
FFCreator中的Effect动画，opacity我感觉跟dom上的不太一样

### ISSUE THREAD

**Issue by rulaishenzhang** [tnfe/FFCreator#75]
hi，你好，我正在打算基于FFCreator开发一个视频编辑的网站，在测试中发现FFCreator的Effect动画中opacity的效果，我感觉跟dom上的不太一样，所以想请教您一下，问题是在哪里。

视频中偏黑色
![WX20210806-183852](https://user-images.githubusercontent.com/6290595/128498427-e10f1fd9-6f7d-46b9-a523-5849e045bb63.png)

dom中
<img width="272" alt="WX20210806-184013@2x" src="https://user-images.githubusercontent.com/6290595/128498530-1f6f3097-4a19-4457-8f0d-1751307fc1bb.png">

dom中我定义的动画与FFcreator一致的

`@keyframes fadeIn {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}`

**Comment by drawcall** [comment]
Well, I am developing the next version, which will replace the new rendering kernel.

**Comment by rulaishenzhang** [comment]
> Oh, I am developing the next version, which will replace the new rendering kernel.

wow，great ！I'm looking forward to the next version.
