### ISSUE TITLE
一个简单版本的 typescript模块提示

### ISSUE THREAD

**Issue by javaswing** [tnfe/FFCreator#76]
如题，在项目中使用到`ffcreator`，写了一简单版本的types。贡献出来，大家可以在这个帖子里补充。自己打算在未来的2两周内，补充一个完整的types提示，并且提交到[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)上。

**Comment by drawcall** [comment]
good job, can you submit a pr

**Comment by javaswing** [comment]
> good job, can you submit a pr

等我这边完善所有类型之后，会提一个pr。请等待

**Comment by javaswing** [comment]
Hi, @drawcall  Now I completed first version types. This is [the link ](https://github.com/javaswing/FFCreator/blob/typescript-types/types/index.d.ts). But I have some question.

- How can i test my code ？ （eg: add ts-node and ts-config file, some ts example）
  please give me some advices
