### ISSUE TITLE
lite版本可以添加两个type一样的animation？

### ISSUE THREAD

**Issue by lyz1991** [tnfe/FFCreator#78]
比如
  text.addAnimate({
      from: {x: w + text.getWidth() / 2, y: h -500 },
      to: { x: w / 2 - text.getWidth() / 2, y: h- 500 },
      delay: 0,
      time: 0.3,
      type: 'move'
    });
    text.addEffect('fadeIn', 1.2, 2)

    text.addAnimate({
      from: {x: w + text.getWidth() / 2, y: h -500 },
      to: { x: w / 2 - text.getWidth() / 2, y: h- 500 },
      delay: 4,
      time: 0.3,
      type: 'move'
    });
发现文字没有出现

**Comment by drawcall** [comment]
Please submit issue in the ffcreatorlite project
