### ISSUE TITLE
Can you provide the two excellent videos' source code? How to make it?

### ISSUE THREAD

**Issue by gclsoft** [tnfe/FFCreator#8]
![image](https://github.com/tnfe/FFCreator/raw/master/docs/_media/imgs/demo/01.gif?raw=true)

![image](https://github.com/tnfe/FFCreator/raw/master/docs/_media/imgs/demo/03.gif?raw=true)

![image](https://user-images.githubusercontent.com/1269898/99622585-6cc75b80-2a65-11eb-879e-c48d69a168c8.png)

**Comment by drawcall** [comment]
Sorry, we can't provide the source code of these two, but it's not complicated to use ffcreator
