### ISSUE TITLE
why cache/xxxxxxxx/video_2_audio.mp3： No Such file or directory

### ISSUE THREAD

**Issue by lyz1991** [tnfe/FFCreator#89]
如题

**Comment by drawcall** [comment]
Please describe your problem in detail

**Comment by lyz1991** [comment]
1. 1. > Please describe your problem in detail

> ``

这个是ffcreator 启动后报错详细内容
![123](https://user-images.githubusercontent.com/15042461/131211060-1abeb18a-a520-4022-ad27-2ca270ab0c86.png)

**Comment by lyz1991** [comment]
> Please describe your problem in detail

这个是creator层还是ffmpeg层出现问题？

**Comment by lyz1991** [comment]
且我只有一次FFVIDEO，为什么id会出现2？

**Comment by lyz1991** [comment]
> Please describe your problem in detail

这个问题，发现是偶现，大概是什么原因呢？

**Comment by drawcall** [comment]
I think you manually deleted the cache folder,

You can upload your project to gh. If you want to process a large number of videos, you can use ffcreatorlite
