### ISSUE TITLE
升级后关于透明度的动画失效了

### ISSUE THREAD

**Issue by lyz1991** [tnfe/FFCreator#90]
3.1.2版本里，addAnimate opacity从0到1的动效到新版本里都直接不展示了

**Comment by drawcall** [comment]
Change the opacity property to alpha

**Comment by lyz1991** [comment]
> Change the opacity property to alpha

可不可以提供，这次change，总共涉及到哪些地方，需要怎么修改？

**Comment by drawcall** [comment]
FFCreator upgrades almost do not need to modify the api, this part is because of the modification of the rendering kernel.

https://github.com/tnfe/FFCreator/blob/master/CHANGELOG.md

**Comment by lyz1991** [comment]
> FFCreator upgrades almost do not need to modify the api, this part is because of the modification of the rendering kernel.
> 
> https://github.com/tnfe/FFCreator/blob/master/CHANGELOG.md

刚才发现旋转角度也变成弧度

**Comment by drawcall** [comment]
Are you interested in this project [https://github.com/tnfe/FFCreator/issues/99](https://github.com/tnfe/FFCreator/issues/99)? Maybe you can try.

**Comment by drawcall** [comment]
Oh, maybe you can use lowcode and ffcreator to create a visual creation video site.
