### ISSUE TITLE
FFText这个api不支持设置textShadow的css效果吗

### ISSUE THREAD

**Issue by rulaishenzhang** [tnfe/FFCreator#94]
FFText这个api不支持设置textShadow的css效果吗

**Comment by drawcall** [comment]
run this demo https://github.com/tnfe/FFCreator/blob/master/examples/text.js

**Comment by rulaishenzhang** [comment]
> run this demo https://github.com/tnfe/FFCreator/blob/master/examples/text.js

你好，很开心支持了这个效果，
但是，我发现不能多层shadow复加，如果可以附加的话，文字会可以制作出很棒的效果哦
`text-shadow: rgb(255 255 255) 1px 1px 0px, rgb(255 255 255) 2px 2px 0px, rgb(219 52 219) 3px 3px 0px, rgb(219 52 219) 4px 4px 0px, rgb(255 190 208) 5px 5px 0px, rgb(255 190 208) 6px 6px 0px, rgb(73 65 51) 7px 7px 0px, rgb(73 65 51) 8px 8px 0px, rgb(125 144 175) 10px 10px 0.2px`

我猜想能否：
  `dropShadow: true,
                    dropShadowColor: ['#ffffff', '#ffffff', '#db34db'],
                    dropShadowBlur: [0,0,0],
                    dropShadowAngle: [Math.PI / 4, Math.PI / 4,Math.PI / 4],
                    dropShadowDistance: [1,2,3],`

我不理解FFCreator的核心逻辑原理，无法通过修改源代码，让他支持多层shadow附加效果。
如果有相关文档说明，我也希望对FFCreator作出贡献，因为我也有不少对于想法。
