### ISSUE TITLE
examples目录下的字幕示例 subtitle.js 生成视频始终有一小段字幕背景在场景中。

### ISSUE THREAD

**Issue by Shijiuwei** [tnfe/FFCreator#97]
把场景Duration加长便于查看那一小段字幕背景
scene1.setDuration(album.getTotalDuration()+5);

https://user-images.githubusercontent.com/526968/131786500-37fc4cae-b782-425f-9ce9-f211a7bd362b.mp4

**Comment by Shijiuwei** [comment]
你们没有这个问题吗？

**Comment by drawcall** [comment]
please download the latest version and it has been fixed.

**Comment by Shijiuwei** [comment]
thank you, is ok!
