### ISSUE TITLE
Based on the lowcode platform and FFCreator, can create a drag-and-drop video site.

### ISSUE THREAD

**Issue by drawcall** [tnfe/FFCreator#99]
For example, based on a lowcode opensource project (https://github.com/ly525/luban-h5 or https://github.com/taowen/awesome-lowcode) and FFCreator with some development work, can create a very interesting project.

I look forward to someone developing it and open source it on github.

![jpg](https://user-images.githubusercontent.com/3407208/131948197-060ed4bf-f5ab-4e0e-a458-a36f40a2505c.png)

**Comment by rulaishenzhang** [comment]
![WX20210903-110205](https://user-images.githubusercontent.com/6290595/131944297-902f3ea2-6507-48e2-b550-c5e7a018e492.png)

![WX20210903-110312](https://user-images.githubusercontent.com/6290595/131944403-53f0bbc6-fc24-4c82-963c-09e3280e7d4c.png)

我正在做这个事情，上面图片是服务器端的渲染代码，让他可以自动获取队列，通过JSON，让FFCrate渲染出视频。

前端编辑器，得等我这个完成以后再开始。

**Comment by drawcall** [comment]
@rulaishenzhang expect, great project.

**Comment by drawcall** [comment]
https://github.com/tnfe/shida
